/* automatically generated by rust-bindgen 0.63.0 */

#![allow(bad_style)]
use ::libc::{pid_t, size_t, ssize_t, FILE};
use ::libelf_sys::*;

#[repr(C)]
pub struct __BindgenUnionField<T>(::std::marker::PhantomData<T>);
impl<T> __BindgenUnionField<T> {
    #[inline]
    pub const fn new() -> Self {
        __BindgenUnionField(::std::marker::PhantomData)
    }
    #[inline]
    pub unsafe fn as_ref(&self) -> &T {
        ::std::mem::transmute(self)
    }
    #[inline]
    pub unsafe fn as_mut(&mut self) -> &mut T {
        ::std::mem::transmute(self)
    }
}
impl<T> ::std::default::Default for __BindgenUnionField<T> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}
impl<T> ::std::clone::Clone for __BindgenUnionField<T> {
    #[inline]
    fn clone(&self) -> Self {
        Self::new()
    }
}
impl<T> ::std::marker::Copy for __BindgenUnionField<T> {}
impl<T> ::std::fmt::Debug for __BindgenUnionField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__BindgenUnionField")
    }
}
impl<T> ::std::hash::Hash for __BindgenUnionField<T> {
    fn hash<H: ::std::hash::Hasher>(&self, _state: &mut H) {}
}
impl<T> ::std::cmp::PartialEq for __BindgenUnionField<T> {
    fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
        true
    }
}
impl<T> ::std::cmp::Eq for __BindgenUnionField<T> {}
pub const DWARF_GETMACROS_START: i32 = -2147483648;
pub const DW_AT_subscr_data: u32 = 10;
pub const DW_AT_element_list: u32 = 15;
pub const DW_AT_member: u32 = 20;
pub const DW_ADDR_none: u32 = 0;
pub mod Dwarf_Cmd {
    pub type Type = ::libc::c_uint;
    pub const DWARF_C_READ: Type = 0;
    pub const DWARF_C_RDWR: Type = 1;
    pub const DWARF_C_WRITE: Type = 2;
}
pub const DWARF_CB_OK: _bindgen_ty_4 = 0;
pub const DWARF_CB_ABORT: _bindgen_ty_4 = 1;
pub type _bindgen_ty_4 = ::libc::c_uint;
pub const DW_TAG_invalid: _bindgen_ty_5 = 0;
pub type _bindgen_ty_5 = ::libc::c_uint;
pub type Dwarf_Off = GElf_Off;
pub type Dwarf_Addr = GElf_Addr;
pub type Dwarf_Word = GElf_Xword;
pub type Dwarf_Sword = GElf_Sxword;
pub type Dwarf_Half = GElf_Half;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Abbrev {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Lines_s {
    _unused: [u8; 0],
}
pub type Dwarf_Lines = Dwarf_Lines_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Line_s {
    _unused: [u8; 0],
}
pub type Dwarf_Line = Dwarf_Line_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Files_s {
    _unused: [u8; 0],
}
pub type Dwarf_Files = Dwarf_Files_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Arange_s {
    _unused: [u8; 0],
}
pub type Dwarf_Arange = Dwarf_Arange_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Aranges_s {
    _unused: [u8; 0],
}
pub type Dwarf_Aranges = Dwarf_Aranges_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_CU {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Macro_s {
    _unused: [u8; 0],
}
pub type Dwarf_Macro = Dwarf_Macro_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Attribute {
    pub code: ::libc::c_uint,
    pub form: ::libc::c_uint,
    pub valp: *mut ::libc::c_uchar,
    pub cu: *mut Dwarf_CU,
}
#[test]
fn bindgen_test_layout_Dwarf_Attribute() {
    const UNINIT: ::std::mem::MaybeUninit<Dwarf_Attribute> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwarf_Attribute>(),
        16usize,
        concat!("Size of: ", stringify!(Dwarf_Attribute))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwarf_Attribute>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwarf_Attribute))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).code) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Attribute),
            "::",
            stringify!(code)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).form) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Attribute),
            "::",
            stringify!(form)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).valp) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Attribute),
            "::",
            stringify!(valp)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cu) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Attribute),
            "::",
            stringify!(cu)
        )
    );
}
#[repr(C)]
pub struct Dwarf_Block {
    pub length: Dwarf_Word,
    pub data: *mut ::libc::c_uchar,
}
#[test]
fn bindgen_test_layout_Dwarf_Block() {
    const UNINIT: ::std::mem::MaybeUninit<Dwarf_Block> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwarf_Block>(),
        12usize,
        concat!("Size of: ", stringify!(Dwarf_Block))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwarf_Block>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwarf_Block))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).length) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Block),
            "::",
            stringify!(length)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).data) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Block),
            "::",
            stringify!(data)
        )
    );
}
impl ::std::fmt::Debug for Dwarf_Block {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "Dwarf_Block {{ data: {:?} }}", self.data)
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Die {
    pub addr: *mut ::libc::c_void,
    pub cu: *mut Dwarf_CU,
    pub abbrev: *mut Dwarf_Abbrev,
    pub padding__: ::libc::c_long,
}
#[test]
fn bindgen_test_layout_Dwarf_Die() {
    const UNINIT: ::std::mem::MaybeUninit<Dwarf_Die> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwarf_Die>(),
        16usize,
        concat!("Size of: ", stringify!(Dwarf_Die))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwarf_Die>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwarf_Die))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).addr) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Die),
            "::",
            stringify!(addr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cu) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Die),
            "::",
            stringify!(cu)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).abbrev) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Die),
            "::",
            stringify!(abbrev)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).padding__) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Die),
            "::",
            stringify!(padding__)
        )
    );
}
#[repr(C)]
pub struct Dwarf_Global {
    pub cu_offset: Dwarf_Off,
    pub die_offset: Dwarf_Off,
    pub name: *const ::libc::c_char,
}
#[test]
fn bindgen_test_layout_Dwarf_Global() {
    const UNINIT: ::std::mem::MaybeUninit<Dwarf_Global> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwarf_Global>(),
        20usize,
        concat!("Size of: ", stringify!(Dwarf_Global))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwarf_Global>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwarf_Global))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cu_offset) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Global),
            "::",
            stringify!(cu_offset)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).die_offset) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Global),
            "::",
            stringify!(die_offset)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Global),
            "::",
            stringify!(name)
        )
    );
}
impl ::std::fmt::Debug for Dwarf_Global {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "Dwarf_Global {{ name: {:?} }}", self.name)
    }
}
#[repr(C)]
pub struct Dwarf_Op {
    pub atom: u8,
    pub number: Dwarf_Word,
    pub number2: Dwarf_Word,
    pub offset: Dwarf_Word,
}
#[test]
fn bindgen_test_layout_Dwarf_Op() {
    const UNINIT: ::std::mem::MaybeUninit<Dwarf_Op> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwarf_Op>(),
        28usize,
        concat!("Size of: ", stringify!(Dwarf_Op))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwarf_Op>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwarf_Op))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).atom) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Op),
            "::",
            stringify!(atom)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).number) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Op),
            "::",
            stringify!(number)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).number2) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Op),
            "::",
            stringify!(number2)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).offset) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_Op),
            "::",
            stringify!(offset)
        )
    );
}
impl ::std::fmt::Debug for Dwarf_Op {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "Dwarf_Op {{  }}")
    }
}
#[repr(C)]
pub struct Dwarf_CIE {
    pub CIE_id: Dwarf_Off,
    pub initial_instructions: *const u8,
    pub initial_instructions_end: *const u8,
    pub code_alignment_factor: Dwarf_Word,
    pub data_alignment_factor: Dwarf_Sword,
    pub return_address_register: Dwarf_Word,
    pub augmentation: *const ::libc::c_char,
    pub augmentation_data: *const u8,
    pub augmentation_data_size: size_t,
    pub fde_augmentation_data_size: size_t,
}
#[test]
fn bindgen_test_layout_Dwarf_CIE() {
    const UNINIT: ::std::mem::MaybeUninit<Dwarf_CIE> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwarf_CIE>(),
        56usize,
        concat!("Size of: ", stringify!(Dwarf_CIE))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwarf_CIE>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwarf_CIE))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).CIE_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(CIE_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).initial_instructions) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(initial_instructions)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).initial_instructions_end) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(initial_instructions_end)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).code_alignment_factor) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(code_alignment_factor)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).data_alignment_factor) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(data_alignment_factor)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).return_address_register) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(return_address_register)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).augmentation) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(augmentation)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).augmentation_data) as usize - ptr as usize },
        44usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(augmentation_data)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).augmentation_data_size) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(augmentation_data_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fde_augmentation_data_size) as usize - ptr as usize },
        52usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CIE),
            "::",
            stringify!(fde_augmentation_data_size)
        )
    );
}
impl ::std::fmt::Debug for Dwarf_CIE {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write ! (f , "Dwarf_CIE {{ initial_instructions: {:?}, initial_instructions_end: {:?}, augmentation: {:?}, augmentation_data: {:?} }}" , self . initial_instructions , self . initial_instructions_end , self . augmentation , self . augmentation_data)
    }
}
#[repr(C)]
pub struct Dwarf_FDE {
    pub CIE_pointer: Dwarf_Off,
    pub start: *const u8,
    pub end: *const u8,
}
#[test]
fn bindgen_test_layout_Dwarf_FDE() {
    const UNINIT: ::std::mem::MaybeUninit<Dwarf_FDE> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwarf_FDE>(),
        16usize,
        concat!("Size of: ", stringify!(Dwarf_FDE))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwarf_FDE>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwarf_FDE))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).CIE_pointer) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_FDE),
            "::",
            stringify!(CIE_pointer)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).start) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_FDE),
            "::",
            stringify!(start)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).end) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_FDE),
            "::",
            stringify!(end)
        )
    );
}
impl ::std::fmt::Debug for Dwarf_FDE {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(
            f,
            "Dwarf_FDE {{ start: {:?}, end: {:?} }}",
            self.start, self.end
        )
    }
}
#[repr(C)]
pub struct Dwarf_CFI_Entry {
    pub CIE_id: __BindgenUnionField<Dwarf_Off>,
    pub cie: __BindgenUnionField<Dwarf_CIE>,
    pub fde: __BindgenUnionField<Dwarf_FDE>,
    pub bindgen_union_field: [u32; 14usize],
}
#[test]
fn bindgen_test_layout_Dwarf_CFI_Entry() {
    const UNINIT: ::std::mem::MaybeUninit<Dwarf_CFI_Entry> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwarf_CFI_Entry>(),
        56usize,
        concat!("Size of: ", stringify!(Dwarf_CFI_Entry))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwarf_CFI_Entry>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwarf_CFI_Entry))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).CIE_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CFI_Entry),
            "::",
            stringify!(CIE_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cie) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CFI_Entry),
            "::",
            stringify!(cie)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fde) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwarf_CFI_Entry),
            "::",
            stringify!(fde)
        )
    );
}
impl ::std::fmt::Debug for Dwarf_CFI_Entry {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, "Dwarf_CFI_Entry {{ union }}")
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_Frame_s {
    _unused: [u8; 0],
}
pub type Dwarf_Frame = Dwarf_Frame_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf_CFI_s {
    _unused: [u8; 0],
}
pub type Dwarf_CFI = Dwarf_CFI_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwarf {
    _unused: [u8; 0],
}
pub type Dwarf_OOM = ::std::option::Option<unsafe extern "C" fn() -> !>;
extern "C" {
    pub fn dwarf_begin(fildes: ::libc::c_int, cmd: Dwarf_Cmd::Type) -> *mut Dwarf;
}
extern "C" {
    pub fn dwarf_begin_elf(elf: *mut Elf, cmd: Dwarf_Cmd::Type, scngrp: *mut Elf_Scn)
        -> *mut Dwarf;
}
extern "C" {
    pub fn dwarf_getelf(dwarf: *mut Dwarf) -> *mut Elf;
}
extern "C" {
    pub fn dwarf_cu_getdwarf(cu: *mut Dwarf_CU) -> *mut Dwarf;
}
extern "C" {
    pub fn dwarf_getalt(main: *mut Dwarf) -> *mut Dwarf;
}
extern "C" {
    pub fn dwarf_setalt(main: *mut Dwarf, alt: *mut Dwarf);
}
extern "C" {
    pub fn dwarf_end(dwarf: *mut Dwarf) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_nextcu(
        dwarf: *mut Dwarf,
        off: Dwarf_Off,
        next_off: *mut Dwarf_Off,
        header_sizep: *mut size_t,
        abbrev_offsetp: *mut Dwarf_Off,
        address_sizep: *mut u8,
        offset_sizep: *mut u8,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_next_unit(
        dwarf: *mut Dwarf,
        off: Dwarf_Off,
        next_off: *mut Dwarf_Off,
        header_sizep: *mut size_t,
        versionp: *mut Dwarf_Half,
        abbrev_offsetp: *mut Dwarf_Off,
        address_sizep: *mut u8,
        offset_sizep: *mut u8,
        type_signaturep: *mut u64,
        type_offsetp: *mut Dwarf_Off,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_get_units(
        dwarf: *mut Dwarf,
        cu: *mut Dwarf_CU,
        next_cu: *mut *mut Dwarf_CU,
        version: *mut Dwarf_Half,
        unit_type: *mut u8,
        cudie: *mut Dwarf_Die,
        subdie: *mut Dwarf_Die,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_cu_info(
        cu: *mut Dwarf_CU,
        version: *mut Dwarf_Half,
        unit_type: *mut u8,
        cudie: *mut Dwarf_Die,
        subdie: *mut Dwarf_Die,
        unit_id: *mut u64,
        address_size: *mut u8,
        offset_size: *mut u8,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_next_cfi(
        e_ident: *const ::libc::c_uchar,
        data: *mut Elf_Data,
        eh_frame_p: bool,
        offset: Dwarf_Off,
        next_offset: *mut Dwarf_Off,
        entry: *mut Dwarf_CFI_Entry,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getcfi(dwarf: *mut Dwarf) -> *mut Dwarf_CFI;
}
extern "C" {
    pub fn dwarf_getcfi_elf(elf: *mut Elf) -> *mut Dwarf_CFI;
}
extern "C" {
    pub fn dwarf_cfi_end(cache: *mut Dwarf_CFI) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_offdie(
        dbg: *mut Dwarf,
        offset: Dwarf_Off,
        result: *mut Dwarf_Die,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwarf_offdie_types(
        dbg: *mut Dwarf,
        offset: Dwarf_Off,
        result: *mut Dwarf_Die,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwarf_dieoffset(die: *mut Dwarf_Die) -> Dwarf_Off;
}
extern "C" {
    pub fn dwarf_cuoffset(die: *mut Dwarf_Die) -> Dwarf_Off;
}
extern "C" {
    pub fn dwarf_diecu(
        die: *mut Dwarf_Die,
        result: *mut Dwarf_Die,
        address_sizep: *mut u8,
        offset_sizep: *mut u8,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwarf_die_addr_die(
        dbg: *mut Dwarf,
        addr: *mut ::libc::c_void,
        result: *mut Dwarf_Die,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwarf_cu_die(
        cu: *mut Dwarf_CU,
        result: *mut Dwarf_Die,
        versionp: *mut Dwarf_Half,
        abbrev_offsetp: *mut Dwarf_Off,
        address_sizep: *mut u8,
        offset_sizep: *mut u8,
        type_signaturep: *mut u64,
        type_offsetp: *mut Dwarf_Off,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwarf_addrdie(
        dbg: *mut Dwarf,
        addr: Dwarf_Addr,
        result: *mut Dwarf_Die,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwarf_child(die: *mut Dwarf_Die, result: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_siblingof(die: *mut Dwarf_Die, result: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_peel_type(die: *mut Dwarf_Die, result: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_haschildren(die: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getattrs(
        die: *mut Dwarf_Die,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut Dwarf_Attribute,
                arg2: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
        offset: isize,
    ) -> isize;
}
extern "C" {
    pub fn dwarf_tag(die: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_attr(
        die: *mut Dwarf_Die,
        search_name: ::libc::c_uint,
        result: *mut Dwarf_Attribute,
    ) -> *mut Dwarf_Attribute;
}
extern "C" {
    pub fn dwarf_hasattr(die: *mut Dwarf_Die, search_name: ::libc::c_uint) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_attr_integrate(
        die: *mut Dwarf_Die,
        search_name: ::libc::c_uint,
        result: *mut Dwarf_Attribute,
    ) -> *mut Dwarf_Attribute;
}
extern "C" {
    pub fn dwarf_hasattr_integrate(
        die: *mut Dwarf_Die,
        search_name: ::libc::c_uint,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_hasform(attr: *mut Dwarf_Attribute, search_form: ::libc::c_uint) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_whatattr(attr: *mut Dwarf_Attribute) -> ::libc::c_uint;
}
extern "C" {
    pub fn dwarf_whatform(attr: *mut Dwarf_Attribute) -> ::libc::c_uint;
}
extern "C" {
    pub fn dwarf_formstring(attrp: *mut Dwarf_Attribute) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwarf_formudata(
        attr: *mut Dwarf_Attribute,
        return_uval: *mut Dwarf_Word,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_formsdata(
        attr: *mut Dwarf_Attribute,
        return_uval: *mut Dwarf_Sword,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_formaddr(
        attr: *mut Dwarf_Attribute,
        return_addr: *mut Dwarf_Addr,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_formref(
        attr: *mut Dwarf_Attribute,
        return_offset: *mut Dwarf_Off,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_formref_die(attr: *mut Dwarf_Attribute, die_mem: *mut Dwarf_Die)
        -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwarf_formblock(
        attr: *mut Dwarf_Attribute,
        return_block: *mut Dwarf_Block,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_formflag(attr: *mut Dwarf_Attribute, return_bool: *mut bool) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_diename(die: *mut Dwarf_Die) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwarf_highpc(die: *mut Dwarf_Die, return_addr: *mut Dwarf_Addr) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lowpc(die: *mut Dwarf_Die, return_addr: *mut Dwarf_Addr) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_entrypc(die: *mut Dwarf_Die, return_addr: *mut Dwarf_Addr) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_haspc(die: *mut Dwarf_Die, pc: Dwarf_Addr) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_ranges(
        die: *mut Dwarf_Die,
        offset: isize,
        basep: *mut Dwarf_Addr,
        startp: *mut Dwarf_Addr,
        endp: *mut Dwarf_Addr,
    ) -> isize;
}
extern "C" {
    pub fn dwarf_bytesize(die: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_bitsize(die: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_bitoffset(die: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_arrayorder(die: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_srclang(die: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getabbrev(
        die: *mut Dwarf_Die,
        offset: Dwarf_Off,
        lengthp: *mut size_t,
    ) -> *mut Dwarf_Abbrev;
}
extern "C" {
    pub fn dwarf_offabbrev(
        dbg: *mut Dwarf,
        offset: Dwarf_Off,
        lengthp: *mut size_t,
        abbrevp: *mut Dwarf_Abbrev,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getabbrevcode(abbrev: *mut Dwarf_Abbrev) -> ::libc::c_uint;
}
extern "C" {
    pub fn dwarf_getabbrevtag(abbrev: *mut Dwarf_Abbrev) -> ::libc::c_uint;
}
extern "C" {
    pub fn dwarf_abbrevhaschildren(abbrev: *mut Dwarf_Abbrev) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getattrcnt(abbrev: *mut Dwarf_Abbrev, attrcntp: *mut size_t) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getabbrevattr(
        abbrev: *mut Dwarf_Abbrev,
        idx: size_t,
        namep: *mut ::libc::c_uint,
        formp: *mut ::libc::c_uint,
        offset: *mut Dwarf_Off,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getabbrevattr_data(
        abbrev: *mut Dwarf_Abbrev,
        idx: size_t,
        namep: *mut ::libc::c_uint,
        formp: *mut ::libc::c_uint,
        datap: *mut Dwarf_Sword,
        offset: *mut Dwarf_Off,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getstring(
        dbg: *mut Dwarf,
        offset: Dwarf_Off,
        lenp: *mut size_t,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwarf_getpubnames(
        dbg: *mut Dwarf,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut Dwarf,
                arg2: *mut Dwarf_Global,
                arg3: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
        offset: isize,
    ) -> isize;
}
extern "C" {
    pub fn dwarf_getsrclines(
        cudie: *mut Dwarf_Die,
        lines: *mut *mut Dwarf_Lines,
        nlines: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_onesrcline(lines: *mut Dwarf_Lines, idx: size_t) -> *mut Dwarf_Line;
}
extern "C" {
    pub fn dwarf_getsrcfiles(
        cudie: *mut Dwarf_Die,
        files: *mut *mut Dwarf_Files,
        nfiles: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getsrc_die(cudie: *mut Dwarf_Die, addr: Dwarf_Addr) -> *mut Dwarf_Line;
}
extern "C" {
    pub fn dwarf_getsrc_file(
        dbg: *mut Dwarf,
        fname: *const ::libc::c_char,
        line: ::libc::c_int,
        col: ::libc::c_int,
        srcsp: *mut *mut *mut Dwarf_Line,
        nsrcs: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lineaddr(line: *mut Dwarf_Line, addrp: *mut Dwarf_Addr) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lineop_index(
        line: *mut Dwarf_Line,
        op_indexp: *mut ::libc::c_uint,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lineno(line: *mut Dwarf_Line, linep: *mut ::libc::c_int) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_linecol(line: *mut Dwarf_Line, colp: *mut ::libc::c_int) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_linebeginstatement(line: *mut Dwarf_Line, flagp: *mut bool) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lineendsequence(line: *mut Dwarf_Line, flagp: *mut bool) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lineblock(line: *mut Dwarf_Line, flagp: *mut bool) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lineprologueend(line: *mut Dwarf_Line, flagp: *mut bool) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lineepiloguebegin(line: *mut Dwarf_Line, flagp: *mut bool) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_lineisa(line: *mut Dwarf_Line, isap: *mut ::libc::c_uint) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_linediscriminator(
        line: *mut Dwarf_Line,
        discp: *mut ::libc::c_uint,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_linesrc(
        line: *mut Dwarf_Line,
        mtime: *mut Dwarf_Word,
        length: *mut Dwarf_Word,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwarf_linecontext(lines: *mut Dwarf_Lines, line: *mut Dwarf_Line) -> *mut Dwarf_Line;
}
extern "C" {
    pub fn dwarf_linefunctionname(dbg: *mut Dwarf, line: *mut Dwarf_Line) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwarf_filesrc(
        file: *mut Dwarf_Files,
        idx: size_t,
        mtime: *mut Dwarf_Word,
        length: *mut Dwarf_Word,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwarf_line_file(
        line: *mut Dwarf_Line,
        files: *mut *mut Dwarf_Files,
        idx: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getsrcdirs(
        files: *mut Dwarf_Files,
        result: *mut *const *const ::libc::c_char,
        ndirs: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_next_lines(
        dwarf: *mut Dwarf,
        off: Dwarf_Off,
        next_off: *mut Dwarf_Off,
        cu: *mut *mut Dwarf_CU,
        srcfiles: *mut *mut Dwarf_Files,
        nfiles: *mut size_t,
        srclines: *mut *mut Dwarf_Lines,
        nlines: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getlocation(
        attr: *mut Dwarf_Attribute,
        expr: *mut *mut Dwarf_Op,
        exprlen: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getlocation_addr(
        attr: *mut Dwarf_Attribute,
        address: Dwarf_Addr,
        exprs: *mut *mut Dwarf_Op,
        exprlens: *mut size_t,
        nlocs: size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getlocations(
        attr: *mut Dwarf_Attribute,
        offset: isize,
        basep: *mut Dwarf_Addr,
        startp: *mut Dwarf_Addr,
        endp: *mut Dwarf_Addr,
        expr: *mut *mut Dwarf_Op,
        exprlen: *mut size_t,
    ) -> isize;
}
extern "C" {
    pub fn dwarf_getlocation_implicit_value(
        attr: *mut Dwarf_Attribute,
        op: *const Dwarf_Op,
        return_block: *mut Dwarf_Block,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getlocation_implicit_pointer(
        attr: *mut Dwarf_Attribute,
        op: *const Dwarf_Op,
        result: *mut Dwarf_Attribute,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getlocation_die(
        attr: *mut Dwarf_Attribute,
        op: *const Dwarf_Op,
        result: *mut Dwarf_Die,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getlocation_attr(
        attr: *mut Dwarf_Attribute,
        op: *const Dwarf_Op,
        result: *mut Dwarf_Attribute,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_aggregate_size(die: *mut Dwarf_Die, size: *mut Dwarf_Word) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_default_lower_bound(
        lang: ::libc::c_int,
        result: *mut Dwarf_Sword,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getscopes(
        cudie: *mut Dwarf_Die,
        pc: Dwarf_Addr,
        scopes: *mut *mut Dwarf_Die,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getscopes_die(die: *mut Dwarf_Die, scopes: *mut *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getscopevar(
        scopes: *mut Dwarf_Die,
        nscopes: ::libc::c_int,
        name: *const ::libc::c_char,
        skip_shadows: ::libc::c_int,
        match_file: *const ::libc::c_char,
        match_lineno: ::libc::c_int,
        match_linecol: ::libc::c_int,
        result: *mut Dwarf_Die,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getaranges(
        dbg: *mut Dwarf,
        aranges: *mut *mut Dwarf_Aranges,
        naranges: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_onearange(aranges: *mut Dwarf_Aranges, idx: size_t) -> *mut Dwarf_Arange;
}
extern "C" {
    pub fn dwarf_getarangeinfo(
        arange: *mut Dwarf_Arange,
        addrp: *mut Dwarf_Addr,
        lengthp: *mut Dwarf_Word,
        offsetp: *mut Dwarf_Off,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getarange_addr(aranges: *mut Dwarf_Aranges, addr: Dwarf_Addr)
        -> *mut Dwarf_Arange;
}
extern "C" {
    pub fn dwarf_getfuncs(
        cudie: *mut Dwarf_Die,
        callback: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut Dwarf_Die, arg2: *mut ::libc::c_void) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
        offset: isize,
    ) -> isize;
}
extern "C" {
    pub fn dwarf_decl_file(decl: *mut Dwarf_Die) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwarf_decl_line(decl: *mut Dwarf_Die, linep: *mut ::libc::c_int) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_decl_column(decl: *mut Dwarf_Die, colp: *mut ::libc::c_int) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_func_inline(func: *mut Dwarf_Die) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_func_inline_instances(
        func: *mut Dwarf_Die,
        callback: ::std::option::Option<
            unsafe extern "C" fn(arg1: *mut Dwarf_Die, arg2: *mut ::libc::c_void) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_entry_breakpoints(
        die: *mut Dwarf_Die,
        bkpts: *mut *mut Dwarf_Addr,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_getmacros(
        cudie: *mut Dwarf_Die,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut Dwarf_Macro,
                arg2: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
        token: isize,
    ) -> isize;
}
extern "C" {
    pub fn dwarf_getmacros_off(
        dbg: *mut Dwarf,
        macoff: Dwarf_Off,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut Dwarf_Macro,
                arg2: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
        token: isize,
    ) -> isize;
}
extern "C" {
    pub fn dwarf_macro_getsrcfiles(
        dbg: *mut Dwarf,
        macro_: *mut Dwarf_Macro,
        files: *mut *mut Dwarf_Files,
        nfiles: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_macro_opcode(
        macro_: *mut Dwarf_Macro,
        opcodep: *mut ::libc::c_uint,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_macro_getparamcnt(
        macro_: *mut Dwarf_Macro,
        paramcntp: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_macro_param(
        macro_: *mut Dwarf_Macro,
        idx: size_t,
        attribute: *mut Dwarf_Attribute,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_macro_param1(macro_: *mut Dwarf_Macro, paramp: *mut Dwarf_Word) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_macro_param2(
        macro_: *mut Dwarf_Macro,
        paramp: *mut Dwarf_Word,
        strp: *mut *const ::libc::c_char,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_cfi_addrframe(
        cache: *mut Dwarf_CFI,
        address: Dwarf_Addr,
        frame: *mut *mut Dwarf_Frame,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_frame_info(
        frame: *mut Dwarf_Frame,
        start: *mut Dwarf_Addr,
        end: *mut Dwarf_Addr,
        signalp: *mut bool,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_frame_cfa(
        frame: *mut Dwarf_Frame,
        ops: *mut *mut Dwarf_Op,
        nops: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_frame_register(
        frame: *mut Dwarf_Frame,
        regno: ::libc::c_int,
        ops_mem: *mut Dwarf_Op,
        ops: *mut *mut Dwarf_Op,
        nops: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_errno() -> ::libc::c_int;
}
extern "C" {
    pub fn dwarf_errmsg(err: ::libc::c_int) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwarf_new_oom_handler(dbg: *mut Dwarf, handler: Dwarf_OOM) -> Dwarf_OOM;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwfl {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwfl_Module {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwfl_Line {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwfl_Thread {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwfl_Frame {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwfl_Callbacks {
    pub find_elf: ::std::option::Option<
        unsafe extern "C" fn(
            mod_: *mut Dwfl_Module,
            userdata: *mut *mut ::libc::c_void,
            modname: *const ::libc::c_char,
            base: Dwarf_Addr,
            file_name: *mut *mut ::libc::c_char,
            elfp: *mut *mut Elf,
        ) -> ::libc::c_int,
    >,
    pub find_debuginfo: ::std::option::Option<
        unsafe extern "C" fn(
            mod_: *mut Dwfl_Module,
            userdata: *mut *mut ::libc::c_void,
            modname: *const ::libc::c_char,
            base: Dwarf_Addr,
            file_name: *const ::libc::c_char,
            debuglink_file: *const ::libc::c_char,
            debuglink_crc: GElf_Word,
            debuginfo_file_name: *mut *mut ::libc::c_char,
        ) -> ::libc::c_int,
    >,
    pub section_address: ::std::option::Option<
        unsafe extern "C" fn(
            mod_: *mut Dwfl_Module,
            userdata: *mut *mut ::libc::c_void,
            modname: *const ::libc::c_char,
            base: Dwarf_Addr,
            secname: *const ::libc::c_char,
            shndx: GElf_Word,
            shdr: *const GElf_Shdr,
            addr: *mut Dwarf_Addr,
        ) -> ::libc::c_int,
    >,
    pub debuginfo_path: *mut *mut ::libc::c_char,
}
#[test]
fn bindgen_test_layout_Dwfl_Callbacks() {
    const UNINIT: ::std::mem::MaybeUninit<Dwfl_Callbacks> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwfl_Callbacks>(),
        16usize,
        concat!("Size of: ", stringify!(Dwfl_Callbacks))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwfl_Callbacks>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwfl_Callbacks))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).find_elf) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Callbacks),
            "::",
            stringify!(find_elf)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).find_debuginfo) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Callbacks),
            "::",
            stringify!(find_debuginfo)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).section_address) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Callbacks),
            "::",
            stringify!(section_address)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).debuginfo_path) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Callbacks),
            "::",
            stringify!(debuginfo_path)
        )
    );
}
extern "C" {
    pub fn dwfl_begin(callbacks: *const Dwfl_Callbacks) -> *mut Dwfl;
}
extern "C" {
    pub fn dwfl_end(arg1: *mut Dwfl);
}
extern "C" {
    pub fn dwfl_version(arg1: *mut Dwfl) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_errno() -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_errmsg(err: ::libc::c_int) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_report_begin(dwfl: *mut Dwfl);
}
extern "C" {
    pub fn dwfl_report_segment(
        dwfl: *mut Dwfl,
        ndx: ::libc::c_int,
        phdr: *const GElf_Phdr,
        bias: GElf_Addr,
        ident: *const ::libc::c_void,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_report_module(
        dwfl: *mut Dwfl,
        name: *const ::libc::c_char,
        start: Dwarf_Addr,
        end: Dwarf_Addr,
    ) -> *mut Dwfl_Module;
}
extern "C" {
    pub fn dwfl_report_elf(
        dwfl: *mut Dwfl,
        name: *const ::libc::c_char,
        file_name: *const ::libc::c_char,
        fd: ::libc::c_int,
        base: GElf_Addr,
        add_p_vaddr: bool,
    ) -> *mut Dwfl_Module;
}
extern "C" {
    pub fn dwfl_report_offline(
        dwfl: *mut Dwfl,
        name: *const ::libc::c_char,
        file_name: *const ::libc::c_char,
        fd: ::libc::c_int,
    ) -> *mut Dwfl_Module;
}
extern "C" {
    pub fn dwfl_report_offline_memory(
        dwfl: *mut Dwfl,
        name: *const ::libc::c_char,
        file_name: *const ::libc::c_char,
        data: *mut ::libc::c_char,
        size: size_t,
    ) -> *mut Dwfl_Module;
}
extern "C" {
    pub fn dwfl_report_end(
        dwfl: *mut Dwfl,
        removed: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut Dwfl_Module,
                arg2: *mut ::libc::c_void,
                arg3: *const ::libc::c_char,
                arg4: Dwarf_Addr,
                arg: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_report_begin_add(dwfl: *mut Dwfl);
}
extern "C" {
    pub fn dwfl_module_info(
        mod_: *mut Dwfl_Module,
        userdata: *mut *mut *mut ::libc::c_void,
        start: *mut Dwarf_Addr,
        end: *mut Dwarf_Addr,
        dwbias: *mut Dwarf_Addr,
        symbias: *mut Dwarf_Addr,
        mainfile: *mut *const ::libc::c_char,
        debugfile: *mut *const ::libc::c_char,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_getmodules(
        dwfl: *mut Dwfl,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut Dwfl_Module,
                arg2: *mut *mut ::libc::c_void,
                arg3: *const ::libc::c_char,
                arg4: Dwarf_Addr,
                arg: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
        offset: isize,
    ) -> isize;
}
extern "C" {
    pub fn dwfl_addrmodule(dwfl: *mut Dwfl, address: Dwarf_Addr) -> *mut Dwfl_Module;
}
extern "C" {
    pub fn dwfl_addrsegment(
        dwfl: *mut Dwfl,
        address: Dwarf_Addr,
        mod_: *mut *mut Dwfl_Module,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_module_report_build_id(
        mod_: *mut Dwfl_Module,
        bits: *const ::libc::c_uchar,
        len: size_t,
        vaddr: GElf_Addr,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_module_build_id(
        mod_: *mut Dwfl_Module,
        bits: *mut *const ::libc::c_uchar,
        vaddr: *mut GElf_Addr,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_build_id_find_elf(
        arg1: *mut Dwfl_Module,
        arg2: *mut *mut ::libc::c_void,
        arg3: *const ::libc::c_char,
        arg4: Dwarf_Addr,
        arg5: *mut *mut ::libc::c_char,
        arg6: *mut *mut Elf,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_build_id_find_debuginfo(
        arg1: *mut Dwfl_Module,
        arg2: *mut *mut ::libc::c_void,
        arg3: *const ::libc::c_char,
        arg4: Dwarf_Addr,
        arg5: *const ::libc::c_char,
        arg6: *const ::libc::c_char,
        arg7: GElf_Word,
        arg8: *mut *mut ::libc::c_char,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_standard_find_debuginfo(
        arg1: *mut Dwfl_Module,
        arg2: *mut *mut ::libc::c_void,
        arg3: *const ::libc::c_char,
        arg4: Dwarf_Addr,
        arg5: *const ::libc::c_char,
        arg6: *const ::libc::c_char,
        arg7: GElf_Word,
        arg8: *mut *mut ::libc::c_char,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_offline_section_address(
        arg1: *mut Dwfl_Module,
        arg2: *mut *mut ::libc::c_void,
        arg3: *const ::libc::c_char,
        arg4: Dwarf_Addr,
        arg5: *const ::libc::c_char,
        arg6: GElf_Word,
        arg7: *const GElf_Shdr,
        addr: *mut Dwarf_Addr,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_kernel_find_elf(
        arg1: *mut Dwfl_Module,
        arg2: *mut *mut ::libc::c_void,
        arg3: *const ::libc::c_char,
        arg4: Dwarf_Addr,
        arg5: *mut *mut ::libc::c_char,
        arg6: *mut *mut Elf,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_kernel_module_section_address(
        arg1: *mut Dwfl_Module,
        arg2: *mut *mut ::libc::c_void,
        arg3: *const ::libc::c_char,
        arg4: Dwarf_Addr,
        arg5: *const ::libc::c_char,
        arg6: GElf_Word,
        arg7: *const GElf_Shdr,
        addr: *mut Dwarf_Addr,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_kernel_report_kernel(dwfl: *mut Dwfl) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_kernel_report_modules(dwfl: *mut Dwfl) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_kernel_report_offline(
        dwfl: *mut Dwfl,
        release: *const ::libc::c_char,
        predicate: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *const ::libc::c_char,
                arg2: *const ::libc::c_char,
            ) -> ::libc::c_int,
        >,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_core_file_report(
        dwfl: *mut Dwfl,
        elf: *mut Elf,
        executable: *const ::libc::c_char,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_proc_report(dwfl: *mut Dwfl, pid: pid_t) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_proc_maps_report(dwfl: *mut Dwfl, arg1: *mut FILE) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_proc_find_elf(
        mod_: *mut Dwfl_Module,
        userdata: *mut *mut ::libc::c_void,
        module_name: *const ::libc::c_char,
        base: Dwarf_Addr,
        file_name: *mut *mut ::libc::c_char,
        arg1: *mut *mut Elf,
    ) -> ::libc::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct argp {
    _unused: [u8; 0],
}
extern "C" {
    pub fn dwfl_standard_argp() -> *const argp;
}
extern "C" {
    #[doc = " Relocation of addresses from Dwfl"]
    pub fn dwfl_module_relocations(mod_: *mut Dwfl_Module) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_module_relocate_address(
        mod_: *mut Dwfl_Module,
        address: *mut Dwarf_Addr,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_module_relocation_info(
        mod_: *mut Dwfl_Module,
        idx: ::libc::c_uint,
        shndxp: *mut GElf_Word,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_validate_address(
        dwfl: *mut Dwfl,
        address: Dwarf_Addr,
        offset: Dwarf_Sword,
    ) -> ::libc::c_int;
}
extern "C" {
    #[doc = " ELF access functions"]
    pub fn dwfl_module_getelf(arg1: *mut Dwfl_Module, bias: *mut GElf_Addr) -> *mut Elf;
}
extern "C" {
    pub fn dwfl_module_getsymtab(mod_: *mut Dwfl_Module) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_module_getsymtab_first_global(mod_: *mut Dwfl_Module) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_module_getsym(
        mod_: *mut Dwfl_Module,
        ndx: ::libc::c_int,
        sym: *mut GElf_Sym,
        shndxp: *mut GElf_Word,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_module_getsym_info(
        mod_: *mut Dwfl_Module,
        ndx: ::libc::c_int,
        sym: *mut GElf_Sym,
        addr: *mut GElf_Addr,
        shndxp: *mut GElf_Word,
        elfp: *mut *mut Elf,
        bias: *mut Dwarf_Addr,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_module_addrname(
        mod_: *mut Dwfl_Module,
        address: GElf_Addr,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_module_addrinfo(
        mod_: *mut Dwfl_Module,
        address: GElf_Addr,
        offset: *mut GElf_Off,
        sym: *mut GElf_Sym,
        shndxp: *mut GElf_Word,
        elfp: *mut *mut Elf,
        bias: *mut Dwarf_Addr,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_module_addrsym(
        mod_: *mut Dwfl_Module,
        address: GElf_Addr,
        sym: *mut GElf_Sym,
        shndxp: *mut GElf_Word,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_module_address_section(
        mod_: *mut Dwfl_Module,
        address: *mut Dwarf_Addr,
        bias: *mut Dwarf_Addr,
    ) -> *mut Elf_Scn;
}
extern "C" {
    #[doc = " Dwarf access functions"]
    pub fn dwfl_module_getdwarf(arg1: *mut Dwfl_Module, bias: *mut Dwarf_Addr) -> *mut Dwarf;
}
extern "C" {
    pub fn dwfl_getdwarf(
        arg1: *mut Dwfl,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut Dwfl_Module,
                arg2: *mut *mut ::libc::c_void,
                arg3: *const ::libc::c_char,
                arg4: Dwarf_Addr,
                arg5: *mut Dwarf,
                arg6: Dwarf_Addr,
                arg7: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
        offset: isize,
    ) -> isize;
}
extern "C" {
    pub fn dwfl_addrdwarf(dwfl: *mut Dwfl, addr: Dwarf_Addr, bias: *mut Dwarf_Addr) -> *mut Dwarf;
}
extern "C" {
    pub fn dwfl_addrdie(dwfl: *mut Dwfl, addr: Dwarf_Addr, bias: *mut Dwarf_Addr)
        -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwfl_module_addrdie(
        mod_: *mut Dwfl_Module,
        addr: Dwarf_Addr,
        bias: *mut Dwarf_Addr,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwfl_nextcu(
        dwfl: *mut Dwfl,
        lastcu: *mut Dwarf_Die,
        bias: *mut Dwarf_Addr,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwfl_module_nextcu(
        mod_: *mut Dwfl_Module,
        lastcu: *mut Dwarf_Die,
        bias: *mut Dwarf_Addr,
    ) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwfl_cumodule(cudie: *mut Dwarf_Die) -> *mut Dwfl_Module;
}
extern "C" {
    pub fn dwfl_getsrclines(cudie: *mut Dwarf_Die, nlines: *mut size_t) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_onesrcline(cudie: *mut Dwarf_Die, idx: size_t) -> *mut Dwfl_Line;
}
extern "C" {
    pub fn dwfl_module_getsrc(mod_: *mut Dwfl_Module, addr: Dwarf_Addr) -> *mut Dwfl_Line;
}
extern "C" {
    pub fn dwfl_getsrc(dwfl: *mut Dwfl, addr: Dwarf_Addr) -> *mut Dwfl_Line;
}
extern "C" {
    pub fn dwfl_module_getsrc_file(
        mod_: *mut Dwfl_Module,
        fname: *const ::libc::c_char,
        lineno: ::libc::c_int,
        column: ::libc::c_int,
        srcsp: *mut *mut *mut Dwfl_Line,
        nsrcs: *mut size_t,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linemodule(line: *mut Dwfl_Line) -> *mut Dwfl_Module;
}
extern "C" {
    pub fn dwfl_linecu(line: *mut Dwfl_Line) -> *mut Dwarf_Die;
}
extern "C" {
    pub fn dwfl_lineinfo(
        line: *mut Dwfl_Line,
        addr: *mut Dwarf_Addr,
        linep: *mut ::libc::c_int,
        colp: *mut ::libc::c_int,
        mtime: *mut Dwarf_Word,
        length: *mut Dwarf_Word,
    ) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwfl_dwarf_line(line: *mut Dwfl_Line, bias: *mut Dwarf_Addr) -> *mut Dwarf_Line;
}
extern "C" {
    pub fn dwfl_line_comp_dir(line: *mut Dwfl_Line) -> *const ::libc::c_char;
}
extern "C" {
    #[doc = " Machine backend access functions"]
    pub fn dwfl_module_return_value_location(
        mod_: *mut Dwfl_Module,
        functypedie: *mut Dwarf_Die,
        locops: *mut *const Dwarf_Op,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_module_register_names(
        mod_: *mut Dwfl_Module,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                arg: *mut ::libc::c_void,
                regno: ::libc::c_int,
                setname: *const ::libc::c_char,
                prefix: *const ::libc::c_char,
                regname: *const ::libc::c_char,
                bits: ::libc::c_int,
                type_: ::libc::c_int,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_module_dwarf_cfi(mod_: *mut Dwfl_Module, bias: *mut Dwarf_Addr) -> *mut Dwarf_CFI;
}
extern "C" {
    pub fn dwfl_module_eh_cfi(mod_: *mut Dwfl_Module, bias: *mut Dwarf_Addr) -> *mut Dwarf_CFI;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwfl_Thread_Callbacks {
    pub next_thread: ::std::option::Option<
        unsafe extern "C" fn(
            dwfl: *mut Dwfl,
            dwfl_arg: *mut ::libc::c_void,
            thread_argp: *mut *mut ::libc::c_void,
        ) -> pid_t,
    >,
    pub get_thread: ::std::option::Option<
        unsafe extern "C" fn(
            dwfl: *mut Dwfl,
            tid: pid_t,
            dwfl_arg: *mut ::libc::c_void,
            thread_argp: *mut *mut ::libc::c_void,
        ) -> bool,
    >,
    pub memory_read: ::std::option::Option<
        unsafe extern "C" fn(
            dwfl: *mut Dwfl,
            addr: Dwarf_Addr,
            result: *mut Dwarf_Word,
            dwfl_arg: *mut ::libc::c_void,
        ) -> bool,
    >,
    pub set_initial_registers: ::std::option::Option<
        unsafe extern "C" fn(thread: *mut Dwfl_Thread, thread_arg: *mut ::libc::c_void) -> bool,
    >,
    pub detach:
        ::std::option::Option<unsafe extern "C" fn(dwfl: *mut Dwfl, dwfl_arg: *mut ::libc::c_void)>,
    pub thread_detach: ::std::option::Option<
        unsafe extern "C" fn(thread: *mut Dwfl_Thread, thread_arg: *mut ::libc::c_void),
    >,
}
#[test]
fn bindgen_test_layout_Dwfl_Thread_Callbacks() {
    const UNINIT: ::std::mem::MaybeUninit<Dwfl_Thread_Callbacks> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<Dwfl_Thread_Callbacks>(),
        24usize,
        concat!("Size of: ", stringify!(Dwfl_Thread_Callbacks))
    );
    assert_eq!(
        ::std::mem::align_of::<Dwfl_Thread_Callbacks>(),
        4usize,
        concat!("Alignment of ", stringify!(Dwfl_Thread_Callbacks))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).next_thread) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Thread_Callbacks),
            "::",
            stringify!(next_thread)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).get_thread) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Thread_Callbacks),
            "::",
            stringify!(get_thread)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).memory_read) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Thread_Callbacks),
            "::",
            stringify!(memory_read)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).set_initial_registers) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Thread_Callbacks),
            "::",
            stringify!(set_initial_registers)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).detach) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Thread_Callbacks),
            "::",
            stringify!(detach)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).thread_detach) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(Dwfl_Thread_Callbacks),
            "::",
            stringify!(thread_detach)
        )
    );
}
extern "C" {
    pub fn dwfl_attach_state(
        dwfl: *mut Dwfl,
        elf: *mut Elf,
        pid: pid_t,
        thread_callbacks: *const Dwfl_Thread_Callbacks,
        dwfl_arg: *mut ::libc::c_void,
    ) -> bool;
}
extern "C" {
    pub fn dwfl_core_file_attach(dwfl: *mut Dwfl, elf: *mut Elf) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_linux_proc_attach(
        dwfl: *mut Dwfl,
        pid: pid_t,
        assume_ptrace_stopped: bool,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_pid(dwfl: *mut Dwfl) -> pid_t;
}
extern "C" {
    pub fn dwfl_thread_dwfl(thread: *mut Dwfl_Thread) -> *mut Dwfl;
}
extern "C" {
    pub fn dwfl_thread_tid(thread: *mut Dwfl_Thread) -> pid_t;
}
extern "C" {
    pub fn dwfl_frame_thread(state: *mut Dwfl_Frame) -> *mut Dwfl_Thread;
}
extern "C" {
    pub fn dwfl_thread_state_registers(
        thread: *mut Dwfl_Thread,
        firstreg: ::libc::c_int,
        nregs: ::libc::c_uint,
        regs: *const Dwarf_Word,
    ) -> bool;
}
extern "C" {
    pub fn dwfl_thread_state_register_pc(thread: *mut Dwfl_Thread, pc: Dwarf_Word);
}
extern "C" {
    pub fn dwfl_getthreads(
        dwfl: *mut Dwfl,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                thread: *mut Dwfl_Thread,
                arg: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_thread_getframes(
        thread: *mut Dwfl_Thread,
        callback: ::std::option::Option<
            unsafe extern "C" fn(state: *mut Dwfl_Frame, arg: *mut ::libc::c_void) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_getthread_frames(
        dwfl: *mut Dwfl,
        tid: pid_t,
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                thread: *mut Dwfl_Frame,
                arg: *mut ::libc::c_void,
            ) -> ::libc::c_int,
        >,
        arg: *mut ::libc::c_void,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwfl_frame_pc(
        state: *mut Dwfl_Frame,
        pc: *mut Dwarf_Addr,
        isactivation: *mut bool,
    ) -> bool;
}
extern "C" {
    pub fn dwfl_frame_reg(
        state: *mut Dwfl_Frame,
        regno: ::libc::c_uint,
        val: *mut Dwarf_Word,
    ) -> ::libc::c_int;
}
extern "C" {
    pub fn dwelf_elf_gnu_debuglink(elf: *mut Elf, crc: *mut GElf_Word) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwelf_dwarf_gnu_debugaltlink(
        dwarf: *mut Dwarf,
        namep: *mut *const ::libc::c_char,
        build_idp: *mut *const ::libc::c_void,
    ) -> ssize_t;
}
extern "C" {
    pub fn dwelf_elf_gnu_build_id(elf: *mut Elf, build_idp: *mut *const ::libc::c_void) -> ssize_t;
}
extern "C" {
    pub fn dwelf_scn_gnu_compressed_size(scn: *mut Elf_Scn) -> ssize_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwelf_Strtab {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Dwelf_Strent {
    _unused: [u8; 0],
}
extern "C" {
    pub fn dwelf_strtab_init(nullstr: bool) -> *mut Dwelf_Strtab;
}
extern "C" {
    pub fn dwelf_strtab_add(
        st: *mut Dwelf_Strtab,
        str_: *const ::libc::c_char,
    ) -> *mut Dwelf_Strent;
}
extern "C" {
    pub fn dwelf_strtab_add_len(
        st: *mut Dwelf_Strtab,
        str_: *const ::libc::c_char,
        len: size_t,
    ) -> *mut Dwelf_Strent;
}
extern "C" {
    pub fn dwelf_strtab_finalize(st: *mut Dwelf_Strtab, data: *mut Elf_Data) -> *mut Elf_Data;
}
extern "C" {
    pub fn dwelf_strent_off(se: *mut Dwelf_Strent) -> size_t;
}
extern "C" {
    pub fn dwelf_strent_str(se: *mut Dwelf_Strent) -> *const ::libc::c_char;
}
extern "C" {
    pub fn dwelf_strtab_free(st: *mut Dwelf_Strtab);
}
extern "C" {
    pub fn dwelf_elf_begin(fd: ::libc::c_int) -> *mut Elf;
}
extern "C" {
    pub fn dwelf_elf_e_machine_string(machine: ::libc::c_int) -> *const ::libc::c_char;
}
pub const DW_UT_compile: _bindgen_ty_6 = 1;
pub const DW_UT_type: _bindgen_ty_6 = 2;
pub const DW_UT_partial: _bindgen_ty_6 = 3;
pub const DW_UT_skeleton: _bindgen_ty_6 = 4;
pub const DW_UT_split_compile: _bindgen_ty_6 = 5;
pub const DW_UT_split_type: _bindgen_ty_6 = 6;
pub const DW_UT_lo_user: _bindgen_ty_6 = 128;
pub const DW_UT_hi_user: _bindgen_ty_6 = 255;
pub type _bindgen_ty_6 = ::libc::c_uint;
pub const DW_TAG_array_type: _bindgen_ty_7 = 1;
pub const DW_TAG_class_type: _bindgen_ty_7 = 2;
pub const DW_TAG_entry_point: _bindgen_ty_7 = 3;
pub const DW_TAG_enumeration_type: _bindgen_ty_7 = 4;
pub const DW_TAG_formal_parameter: _bindgen_ty_7 = 5;
pub const DW_TAG_imported_declaration: _bindgen_ty_7 = 8;
pub const DW_TAG_label: _bindgen_ty_7 = 10;
pub const DW_TAG_lexical_block: _bindgen_ty_7 = 11;
pub const DW_TAG_member: _bindgen_ty_7 = 13;
pub const DW_TAG_pointer_type: _bindgen_ty_7 = 15;
pub const DW_TAG_reference_type: _bindgen_ty_7 = 16;
pub const DW_TAG_compile_unit: _bindgen_ty_7 = 17;
pub const DW_TAG_string_type: _bindgen_ty_7 = 18;
pub const DW_TAG_structure_type: _bindgen_ty_7 = 19;
pub const DW_TAG_subroutine_type: _bindgen_ty_7 = 21;
pub const DW_TAG_typedef: _bindgen_ty_7 = 22;
pub const DW_TAG_union_type: _bindgen_ty_7 = 23;
pub const DW_TAG_unspecified_parameters: _bindgen_ty_7 = 24;
pub const DW_TAG_variant: _bindgen_ty_7 = 25;
pub const DW_TAG_common_block: _bindgen_ty_7 = 26;
pub const DW_TAG_common_inclusion: _bindgen_ty_7 = 27;
pub const DW_TAG_inheritance: _bindgen_ty_7 = 28;
pub const DW_TAG_inlined_subroutine: _bindgen_ty_7 = 29;
pub const DW_TAG_module: _bindgen_ty_7 = 30;
pub const DW_TAG_ptr_to_member_type: _bindgen_ty_7 = 31;
pub const DW_TAG_set_type: _bindgen_ty_7 = 32;
pub const DW_TAG_subrange_type: _bindgen_ty_7 = 33;
pub const DW_TAG_with_stmt: _bindgen_ty_7 = 34;
pub const DW_TAG_access_declaration: _bindgen_ty_7 = 35;
pub const DW_TAG_base_type: _bindgen_ty_7 = 36;
pub const DW_TAG_catch_block: _bindgen_ty_7 = 37;
pub const DW_TAG_const_type: _bindgen_ty_7 = 38;
pub const DW_TAG_constant: _bindgen_ty_7 = 39;
pub const DW_TAG_enumerator: _bindgen_ty_7 = 40;
pub const DW_TAG_file_type: _bindgen_ty_7 = 41;
pub const DW_TAG_friend: _bindgen_ty_7 = 42;
pub const DW_TAG_namelist: _bindgen_ty_7 = 43;
pub const DW_TAG_namelist_item: _bindgen_ty_7 = 44;
pub const DW_TAG_packed_type: _bindgen_ty_7 = 45;
pub const DW_TAG_subprogram: _bindgen_ty_7 = 46;
pub const DW_TAG_template_type_parameter: _bindgen_ty_7 = 47;
pub const DW_TAG_template_value_parameter: _bindgen_ty_7 = 48;
pub const DW_TAG_thrown_type: _bindgen_ty_7 = 49;
pub const DW_TAG_try_block: _bindgen_ty_7 = 50;
pub const DW_TAG_variant_part: _bindgen_ty_7 = 51;
pub const DW_TAG_variable: _bindgen_ty_7 = 52;
pub const DW_TAG_volatile_type: _bindgen_ty_7 = 53;
pub const DW_TAG_dwarf_procedure: _bindgen_ty_7 = 54;
pub const DW_TAG_restrict_type: _bindgen_ty_7 = 55;
pub const DW_TAG_interface_type: _bindgen_ty_7 = 56;
pub const DW_TAG_namespace: _bindgen_ty_7 = 57;
pub const DW_TAG_imported_module: _bindgen_ty_7 = 58;
pub const DW_TAG_unspecified_type: _bindgen_ty_7 = 59;
pub const DW_TAG_partial_unit: _bindgen_ty_7 = 60;
pub const DW_TAG_imported_unit: _bindgen_ty_7 = 61;
pub const DW_TAG_condition: _bindgen_ty_7 = 63;
pub const DW_TAG_shared_type: _bindgen_ty_7 = 64;
pub const DW_TAG_type_unit: _bindgen_ty_7 = 65;
pub const DW_TAG_rvalue_reference_type: _bindgen_ty_7 = 66;
pub const DW_TAG_template_alias: _bindgen_ty_7 = 67;
pub const DW_TAG_coarray_type: _bindgen_ty_7 = 68;
pub const DW_TAG_generic_subrange: _bindgen_ty_7 = 69;
pub const DW_TAG_dynamic_type: _bindgen_ty_7 = 70;
pub const DW_TAG_atomic_type: _bindgen_ty_7 = 71;
pub const DW_TAG_call_site: _bindgen_ty_7 = 72;
pub const DW_TAG_call_site_parameter: _bindgen_ty_7 = 73;
pub const DW_TAG_skeleton_unit: _bindgen_ty_7 = 74;
pub const DW_TAG_immutable_type: _bindgen_ty_7 = 75;
pub const DW_TAG_lo_user: _bindgen_ty_7 = 16512;
pub const DW_TAG_MIPS_loop: _bindgen_ty_7 = 16513;
pub const DW_TAG_format_label: _bindgen_ty_7 = 16641;
pub const DW_TAG_function_template: _bindgen_ty_7 = 16642;
pub const DW_TAG_class_template: _bindgen_ty_7 = 16643;
pub const DW_TAG_GNU_BINCL: _bindgen_ty_7 = 16644;
pub const DW_TAG_GNU_EINCL: _bindgen_ty_7 = 16645;
pub const DW_TAG_GNU_template_template_param: _bindgen_ty_7 = 16646;
pub const DW_TAG_GNU_template_parameter_pack: _bindgen_ty_7 = 16647;
pub const DW_TAG_GNU_formal_parameter_pack: _bindgen_ty_7 = 16648;
pub const DW_TAG_GNU_call_site: _bindgen_ty_7 = 16649;
pub const DW_TAG_GNU_call_site_parameter: _bindgen_ty_7 = 16650;
pub const DW_TAG_hi_user: _bindgen_ty_7 = 65535;
pub type _bindgen_ty_7 = ::libc::c_uint;
pub const DW_CHILDREN_no: _bindgen_ty_8 = 0;
pub const DW_CHILDREN_yes: _bindgen_ty_8 = 1;
pub type _bindgen_ty_8 = ::libc::c_uint;
pub const DW_AT_sibling: _bindgen_ty_9 = 1;
pub const DW_AT_location: _bindgen_ty_9 = 2;
pub const DW_AT_name: _bindgen_ty_9 = 3;
pub const DW_AT_ordering: _bindgen_ty_9 = 9;
pub const DW_AT_byte_size: _bindgen_ty_9 = 11;
pub const DW_AT_bit_offset: _bindgen_ty_9 = 12;
pub const DW_AT_bit_size: _bindgen_ty_9 = 13;
pub const DW_AT_stmt_list: _bindgen_ty_9 = 16;
pub const DW_AT_low_pc: _bindgen_ty_9 = 17;
pub const DW_AT_high_pc: _bindgen_ty_9 = 18;
pub const DW_AT_language: _bindgen_ty_9 = 19;
pub const DW_AT_discr: _bindgen_ty_9 = 21;
pub const DW_AT_discr_value: _bindgen_ty_9 = 22;
pub const DW_AT_visibility: _bindgen_ty_9 = 23;
pub const DW_AT_import: _bindgen_ty_9 = 24;
pub const DW_AT_string_length: _bindgen_ty_9 = 25;
pub const DW_AT_common_reference: _bindgen_ty_9 = 26;
pub const DW_AT_comp_dir: _bindgen_ty_9 = 27;
pub const DW_AT_const_value: _bindgen_ty_9 = 28;
pub const DW_AT_containing_type: _bindgen_ty_9 = 29;
pub const DW_AT_default_value: _bindgen_ty_9 = 30;
pub const DW_AT_inline: _bindgen_ty_9 = 32;
pub const DW_AT_is_optional: _bindgen_ty_9 = 33;
pub const DW_AT_lower_bound: _bindgen_ty_9 = 34;
pub const DW_AT_producer: _bindgen_ty_9 = 37;
pub const DW_AT_prototyped: _bindgen_ty_9 = 39;
pub const DW_AT_return_addr: _bindgen_ty_9 = 42;
pub const DW_AT_start_scope: _bindgen_ty_9 = 44;
pub const DW_AT_bit_stride: _bindgen_ty_9 = 46;
pub const DW_AT_upper_bound: _bindgen_ty_9 = 47;
pub const DW_AT_abstract_origin: _bindgen_ty_9 = 49;
pub const DW_AT_accessibility: _bindgen_ty_9 = 50;
pub const DW_AT_address_class: _bindgen_ty_9 = 51;
pub const DW_AT_artificial: _bindgen_ty_9 = 52;
pub const DW_AT_base_types: _bindgen_ty_9 = 53;
pub const DW_AT_calling_convention: _bindgen_ty_9 = 54;
pub const DW_AT_count: _bindgen_ty_9 = 55;
pub const DW_AT_data_member_location: _bindgen_ty_9 = 56;
pub const DW_AT_decl_column: _bindgen_ty_9 = 57;
pub const DW_AT_decl_file: _bindgen_ty_9 = 58;
pub const DW_AT_decl_line: _bindgen_ty_9 = 59;
pub const DW_AT_declaration: _bindgen_ty_9 = 60;
pub const DW_AT_discr_list: _bindgen_ty_9 = 61;
pub const DW_AT_encoding: _bindgen_ty_9 = 62;
pub const DW_AT_external: _bindgen_ty_9 = 63;
pub const DW_AT_frame_base: _bindgen_ty_9 = 64;
pub const DW_AT_friend: _bindgen_ty_9 = 65;
pub const DW_AT_identifier_case: _bindgen_ty_9 = 66;
pub const DW_AT_macro_info: _bindgen_ty_9 = 67;
pub const DW_AT_namelist_item: _bindgen_ty_9 = 68;
pub const DW_AT_priority: _bindgen_ty_9 = 69;
pub const DW_AT_segment: _bindgen_ty_9 = 70;
pub const DW_AT_specification: _bindgen_ty_9 = 71;
pub const DW_AT_static_link: _bindgen_ty_9 = 72;
pub const DW_AT_type: _bindgen_ty_9 = 73;
pub const DW_AT_use_location: _bindgen_ty_9 = 74;
pub const DW_AT_variable_parameter: _bindgen_ty_9 = 75;
pub const DW_AT_virtuality: _bindgen_ty_9 = 76;
pub const DW_AT_vtable_elem_location: _bindgen_ty_9 = 77;
pub const DW_AT_allocated: _bindgen_ty_9 = 78;
pub const DW_AT_associated: _bindgen_ty_9 = 79;
pub const DW_AT_data_location: _bindgen_ty_9 = 80;
pub const DW_AT_byte_stride: _bindgen_ty_9 = 81;
pub const DW_AT_entry_pc: _bindgen_ty_9 = 82;
pub const DW_AT_use_UTF8: _bindgen_ty_9 = 83;
pub const DW_AT_extension: _bindgen_ty_9 = 84;
pub const DW_AT_ranges: _bindgen_ty_9 = 85;
pub const DW_AT_trampoline: _bindgen_ty_9 = 86;
pub const DW_AT_call_column: _bindgen_ty_9 = 87;
pub const DW_AT_call_file: _bindgen_ty_9 = 88;
pub const DW_AT_call_line: _bindgen_ty_9 = 89;
pub const DW_AT_description: _bindgen_ty_9 = 90;
pub const DW_AT_binary_scale: _bindgen_ty_9 = 91;
pub const DW_AT_decimal_scale: _bindgen_ty_9 = 92;
pub const DW_AT_small: _bindgen_ty_9 = 93;
pub const DW_AT_decimal_sign: _bindgen_ty_9 = 94;
pub const DW_AT_digit_count: _bindgen_ty_9 = 95;
pub const DW_AT_picture_string: _bindgen_ty_9 = 96;
pub const DW_AT_mutable: _bindgen_ty_9 = 97;
pub const DW_AT_threads_scaled: _bindgen_ty_9 = 98;
pub const DW_AT_explicit: _bindgen_ty_9 = 99;
pub const DW_AT_object_pointer: _bindgen_ty_9 = 100;
pub const DW_AT_endianity: _bindgen_ty_9 = 101;
pub const DW_AT_elemental: _bindgen_ty_9 = 102;
pub const DW_AT_pure: _bindgen_ty_9 = 103;
pub const DW_AT_recursive: _bindgen_ty_9 = 104;
pub const DW_AT_signature: _bindgen_ty_9 = 105;
pub const DW_AT_main_subprogram: _bindgen_ty_9 = 106;
pub const DW_AT_data_bit_offset: _bindgen_ty_9 = 107;
pub const DW_AT_const_expr: _bindgen_ty_9 = 108;
pub const DW_AT_enum_class: _bindgen_ty_9 = 109;
pub const DW_AT_linkage_name: _bindgen_ty_9 = 110;
pub const DW_AT_string_length_bit_size: _bindgen_ty_9 = 111;
pub const DW_AT_string_length_byte_size: _bindgen_ty_9 = 112;
pub const DW_AT_rank: _bindgen_ty_9 = 113;
pub const DW_AT_str_offsets_base: _bindgen_ty_9 = 114;
pub const DW_AT_addr_base: _bindgen_ty_9 = 115;
pub const DW_AT_rnglists_base: _bindgen_ty_9 = 116;
pub const DW_AT_dwo_name: _bindgen_ty_9 = 118;
pub const DW_AT_reference: _bindgen_ty_9 = 119;
pub const DW_AT_rvalue_reference: _bindgen_ty_9 = 120;
pub const DW_AT_macros: _bindgen_ty_9 = 121;
pub const DW_AT_call_all_calls: _bindgen_ty_9 = 122;
pub const DW_AT_call_all_source_calls: _bindgen_ty_9 = 123;
pub const DW_AT_call_all_tail_calls: _bindgen_ty_9 = 124;
pub const DW_AT_call_return_pc: _bindgen_ty_9 = 125;
pub const DW_AT_call_value: _bindgen_ty_9 = 126;
pub const DW_AT_call_origin: _bindgen_ty_9 = 127;
pub const DW_AT_call_parameter: _bindgen_ty_9 = 128;
pub const DW_AT_call_pc: _bindgen_ty_9 = 129;
pub const DW_AT_call_tail_call: _bindgen_ty_9 = 130;
pub const DW_AT_call_target: _bindgen_ty_9 = 131;
pub const DW_AT_call_target_clobbered: _bindgen_ty_9 = 132;
pub const DW_AT_call_data_location: _bindgen_ty_9 = 133;
pub const DW_AT_call_data_value: _bindgen_ty_9 = 134;
pub const DW_AT_noreturn: _bindgen_ty_9 = 135;
pub const DW_AT_alignment: _bindgen_ty_9 = 136;
pub const DW_AT_export_symbols: _bindgen_ty_9 = 137;
pub const DW_AT_deleted: _bindgen_ty_9 = 138;
pub const DW_AT_defaulted: _bindgen_ty_9 = 139;
pub const DW_AT_loclists_base: _bindgen_ty_9 = 140;
pub const DW_AT_lo_user: _bindgen_ty_9 = 8192;
pub const DW_AT_MIPS_fde: _bindgen_ty_9 = 8193;
pub const DW_AT_MIPS_loop_begin: _bindgen_ty_9 = 8194;
pub const DW_AT_MIPS_tail_loop_begin: _bindgen_ty_9 = 8195;
pub const DW_AT_MIPS_epilog_begin: _bindgen_ty_9 = 8196;
pub const DW_AT_MIPS_loop_unroll_factor: _bindgen_ty_9 = 8197;
pub const DW_AT_MIPS_software_pipeline_depth: _bindgen_ty_9 = 8198;
pub const DW_AT_MIPS_linkage_name: _bindgen_ty_9 = 8199;
pub const DW_AT_MIPS_stride: _bindgen_ty_9 = 8200;
pub const DW_AT_MIPS_abstract_name: _bindgen_ty_9 = 8201;
pub const DW_AT_MIPS_clone_origin: _bindgen_ty_9 = 8202;
pub const DW_AT_MIPS_has_inlines: _bindgen_ty_9 = 8203;
pub const DW_AT_MIPS_stride_byte: _bindgen_ty_9 = 8204;
pub const DW_AT_MIPS_stride_elem: _bindgen_ty_9 = 8205;
pub const DW_AT_MIPS_ptr_dopetype: _bindgen_ty_9 = 8206;
pub const DW_AT_MIPS_allocatable_dopetype: _bindgen_ty_9 = 8207;
pub const DW_AT_MIPS_assumed_shape_dopetype: _bindgen_ty_9 = 8208;
pub const DW_AT_MIPS_assumed_size: _bindgen_ty_9 = 8209;
pub const DW_AT_sf_names: _bindgen_ty_9 = 8449;
pub const DW_AT_src_info: _bindgen_ty_9 = 8450;
pub const DW_AT_mac_info: _bindgen_ty_9 = 8451;
pub const DW_AT_src_coords: _bindgen_ty_9 = 8452;
pub const DW_AT_body_begin: _bindgen_ty_9 = 8453;
pub const DW_AT_body_end: _bindgen_ty_9 = 8454;
pub const DW_AT_GNU_vector: _bindgen_ty_9 = 8455;
pub const DW_AT_GNU_guarded_by: _bindgen_ty_9 = 8456;
pub const DW_AT_GNU_pt_guarded_by: _bindgen_ty_9 = 8457;
pub const DW_AT_GNU_guarded: _bindgen_ty_9 = 8458;
pub const DW_AT_GNU_pt_guarded: _bindgen_ty_9 = 8459;
pub const DW_AT_GNU_locks_excluded: _bindgen_ty_9 = 8460;
pub const DW_AT_GNU_exclusive_locks_required: _bindgen_ty_9 = 8461;
pub const DW_AT_GNU_shared_locks_required: _bindgen_ty_9 = 8462;
pub const DW_AT_GNU_odr_signature: _bindgen_ty_9 = 8463;
pub const DW_AT_GNU_template_name: _bindgen_ty_9 = 8464;
pub const DW_AT_GNU_call_site_value: _bindgen_ty_9 = 8465;
pub const DW_AT_GNU_call_site_data_value: _bindgen_ty_9 = 8466;
pub const DW_AT_GNU_call_site_target: _bindgen_ty_9 = 8467;
pub const DW_AT_GNU_call_site_target_clobbered: _bindgen_ty_9 = 8468;
pub const DW_AT_GNU_tail_call: _bindgen_ty_9 = 8469;
pub const DW_AT_GNU_all_tail_call_sites: _bindgen_ty_9 = 8470;
pub const DW_AT_GNU_all_call_sites: _bindgen_ty_9 = 8471;
pub const DW_AT_GNU_all_source_call_sites: _bindgen_ty_9 = 8472;
pub const DW_AT_GNU_locviews: _bindgen_ty_9 = 8503;
pub const DW_AT_GNU_entry_view: _bindgen_ty_9 = 8504;
pub const DW_AT_GNU_macros: _bindgen_ty_9 = 8473;
pub const DW_AT_GNU_deleted: _bindgen_ty_9 = 8474;
pub const DW_AT_GNU_dwo_name: _bindgen_ty_9 = 8496;
pub const DW_AT_GNU_dwo_id: _bindgen_ty_9 = 8497;
pub const DW_AT_GNU_ranges_base: _bindgen_ty_9 = 8498;
pub const DW_AT_GNU_addr_base: _bindgen_ty_9 = 8499;
pub const DW_AT_GNU_pubnames: _bindgen_ty_9 = 8500;
pub const DW_AT_GNU_pubtypes: _bindgen_ty_9 = 8501;
pub const DW_AT_GNU_numerator: _bindgen_ty_9 = 8963;
pub const DW_AT_GNU_denominator: _bindgen_ty_9 = 8964;
pub const DW_AT_GNU_bias: _bindgen_ty_9 = 8965;
pub const DW_AT_hi_user: _bindgen_ty_9 = 16383;
pub type _bindgen_ty_9 = ::libc::c_uint;
pub const DW_FORM_addr: _bindgen_ty_10 = 1;
pub const DW_FORM_block2: _bindgen_ty_10 = 3;
pub const DW_FORM_block4: _bindgen_ty_10 = 4;
pub const DW_FORM_data2: _bindgen_ty_10 = 5;
pub const DW_FORM_data4: _bindgen_ty_10 = 6;
pub const DW_FORM_data8: _bindgen_ty_10 = 7;
pub const DW_FORM_string: _bindgen_ty_10 = 8;
pub const DW_FORM_block: _bindgen_ty_10 = 9;
pub const DW_FORM_block1: _bindgen_ty_10 = 10;
pub const DW_FORM_data1: _bindgen_ty_10 = 11;
pub const DW_FORM_flag: _bindgen_ty_10 = 12;
pub const DW_FORM_sdata: _bindgen_ty_10 = 13;
pub const DW_FORM_strp: _bindgen_ty_10 = 14;
pub const DW_FORM_udata: _bindgen_ty_10 = 15;
pub const DW_FORM_ref_addr: _bindgen_ty_10 = 16;
pub const DW_FORM_ref1: _bindgen_ty_10 = 17;
pub const DW_FORM_ref2: _bindgen_ty_10 = 18;
pub const DW_FORM_ref4: _bindgen_ty_10 = 19;
pub const DW_FORM_ref8: _bindgen_ty_10 = 20;
pub const DW_FORM_ref_udata: _bindgen_ty_10 = 21;
pub const DW_FORM_indirect: _bindgen_ty_10 = 22;
pub const DW_FORM_sec_offset: _bindgen_ty_10 = 23;
pub const DW_FORM_exprloc: _bindgen_ty_10 = 24;
pub const DW_FORM_flag_present: _bindgen_ty_10 = 25;
pub const DW_FORM_strx: _bindgen_ty_10 = 26;
pub const DW_FORM_addrx: _bindgen_ty_10 = 27;
pub const DW_FORM_ref_sup4: _bindgen_ty_10 = 28;
pub const DW_FORM_strp_sup: _bindgen_ty_10 = 29;
pub const DW_FORM_data16: _bindgen_ty_10 = 30;
pub const DW_FORM_line_strp: _bindgen_ty_10 = 31;
pub const DW_FORM_ref_sig8: _bindgen_ty_10 = 32;
pub const DW_FORM_implicit_const: _bindgen_ty_10 = 33;
pub const DW_FORM_loclistx: _bindgen_ty_10 = 34;
pub const DW_FORM_rnglistx: _bindgen_ty_10 = 35;
pub const DW_FORM_ref_sup8: _bindgen_ty_10 = 36;
pub const DW_FORM_strx1: _bindgen_ty_10 = 37;
pub const DW_FORM_strx2: _bindgen_ty_10 = 38;
pub const DW_FORM_strx3: _bindgen_ty_10 = 39;
pub const DW_FORM_strx4: _bindgen_ty_10 = 40;
pub const DW_FORM_addrx1: _bindgen_ty_10 = 41;
pub const DW_FORM_addrx2: _bindgen_ty_10 = 42;
pub const DW_FORM_addrx3: _bindgen_ty_10 = 43;
pub const DW_FORM_addrx4: _bindgen_ty_10 = 44;
pub const DW_FORM_GNU_addr_index: _bindgen_ty_10 = 7937;
pub const DW_FORM_GNU_str_index: _bindgen_ty_10 = 7938;
pub const DW_FORM_GNU_ref_alt: _bindgen_ty_10 = 7968;
pub const DW_FORM_GNU_strp_alt: _bindgen_ty_10 = 7969;
pub type _bindgen_ty_10 = ::libc::c_uint;
pub const DW_OP_addr: _bindgen_ty_11 = 3;
pub const DW_OP_deref: _bindgen_ty_11 = 6;
pub const DW_OP_const1u: _bindgen_ty_11 = 8;
pub const DW_OP_const1s: _bindgen_ty_11 = 9;
pub const DW_OP_const2u: _bindgen_ty_11 = 10;
pub const DW_OP_const2s: _bindgen_ty_11 = 11;
pub const DW_OP_const4u: _bindgen_ty_11 = 12;
pub const DW_OP_const4s: _bindgen_ty_11 = 13;
pub const DW_OP_const8u: _bindgen_ty_11 = 14;
pub const DW_OP_const8s: _bindgen_ty_11 = 15;
pub const DW_OP_constu: _bindgen_ty_11 = 16;
pub const DW_OP_consts: _bindgen_ty_11 = 17;
pub const DW_OP_dup: _bindgen_ty_11 = 18;
pub const DW_OP_drop: _bindgen_ty_11 = 19;
pub const DW_OP_over: _bindgen_ty_11 = 20;
pub const DW_OP_pick: _bindgen_ty_11 = 21;
pub const DW_OP_swap: _bindgen_ty_11 = 22;
pub const DW_OP_rot: _bindgen_ty_11 = 23;
pub const DW_OP_xderef: _bindgen_ty_11 = 24;
pub const DW_OP_abs: _bindgen_ty_11 = 25;
pub const DW_OP_and: _bindgen_ty_11 = 26;
pub const DW_OP_div: _bindgen_ty_11 = 27;
pub const DW_OP_minus: _bindgen_ty_11 = 28;
pub const DW_OP_mod: _bindgen_ty_11 = 29;
pub const DW_OP_mul: _bindgen_ty_11 = 30;
pub const DW_OP_neg: _bindgen_ty_11 = 31;
pub const DW_OP_not: _bindgen_ty_11 = 32;
pub const DW_OP_or: _bindgen_ty_11 = 33;
pub const DW_OP_plus: _bindgen_ty_11 = 34;
pub const DW_OP_plus_uconst: _bindgen_ty_11 = 35;
pub const DW_OP_shl: _bindgen_ty_11 = 36;
pub const DW_OP_shr: _bindgen_ty_11 = 37;
pub const DW_OP_shra: _bindgen_ty_11 = 38;
pub const DW_OP_xor: _bindgen_ty_11 = 39;
pub const DW_OP_bra: _bindgen_ty_11 = 40;
pub const DW_OP_eq: _bindgen_ty_11 = 41;
pub const DW_OP_ge: _bindgen_ty_11 = 42;
pub const DW_OP_gt: _bindgen_ty_11 = 43;
pub const DW_OP_le: _bindgen_ty_11 = 44;
pub const DW_OP_lt: _bindgen_ty_11 = 45;
pub const DW_OP_ne: _bindgen_ty_11 = 46;
pub const DW_OP_skip: _bindgen_ty_11 = 47;
pub const DW_OP_lit0: _bindgen_ty_11 = 48;
pub const DW_OP_lit1: _bindgen_ty_11 = 49;
pub const DW_OP_lit2: _bindgen_ty_11 = 50;
pub const DW_OP_lit3: _bindgen_ty_11 = 51;
pub const DW_OP_lit4: _bindgen_ty_11 = 52;
pub const DW_OP_lit5: _bindgen_ty_11 = 53;
pub const DW_OP_lit6: _bindgen_ty_11 = 54;
pub const DW_OP_lit7: _bindgen_ty_11 = 55;
pub const DW_OP_lit8: _bindgen_ty_11 = 56;
pub const DW_OP_lit9: _bindgen_ty_11 = 57;
pub const DW_OP_lit10: _bindgen_ty_11 = 58;
pub const DW_OP_lit11: _bindgen_ty_11 = 59;
pub const DW_OP_lit12: _bindgen_ty_11 = 60;
pub const DW_OP_lit13: _bindgen_ty_11 = 61;
pub const DW_OP_lit14: _bindgen_ty_11 = 62;
pub const DW_OP_lit15: _bindgen_ty_11 = 63;
pub const DW_OP_lit16: _bindgen_ty_11 = 64;
pub const DW_OP_lit17: _bindgen_ty_11 = 65;
pub const DW_OP_lit18: _bindgen_ty_11 = 66;
pub const DW_OP_lit19: _bindgen_ty_11 = 67;
pub const DW_OP_lit20: _bindgen_ty_11 = 68;
pub const DW_OP_lit21: _bindgen_ty_11 = 69;
pub const DW_OP_lit22: _bindgen_ty_11 = 70;
pub const DW_OP_lit23: _bindgen_ty_11 = 71;
pub const DW_OP_lit24: _bindgen_ty_11 = 72;
pub const DW_OP_lit25: _bindgen_ty_11 = 73;
pub const DW_OP_lit26: _bindgen_ty_11 = 74;
pub const DW_OP_lit27: _bindgen_ty_11 = 75;
pub const DW_OP_lit28: _bindgen_ty_11 = 76;
pub const DW_OP_lit29: _bindgen_ty_11 = 77;
pub const DW_OP_lit30: _bindgen_ty_11 = 78;
pub const DW_OP_lit31: _bindgen_ty_11 = 79;
pub const DW_OP_reg0: _bindgen_ty_11 = 80;
pub const DW_OP_reg1: _bindgen_ty_11 = 81;
pub const DW_OP_reg2: _bindgen_ty_11 = 82;
pub const DW_OP_reg3: _bindgen_ty_11 = 83;
pub const DW_OP_reg4: _bindgen_ty_11 = 84;
pub const DW_OP_reg5: _bindgen_ty_11 = 85;
pub const DW_OP_reg6: _bindgen_ty_11 = 86;
pub const DW_OP_reg7: _bindgen_ty_11 = 87;
pub const DW_OP_reg8: _bindgen_ty_11 = 88;
pub const DW_OP_reg9: _bindgen_ty_11 = 89;
pub const DW_OP_reg10: _bindgen_ty_11 = 90;
pub const DW_OP_reg11: _bindgen_ty_11 = 91;
pub const DW_OP_reg12: _bindgen_ty_11 = 92;
pub const DW_OP_reg13: _bindgen_ty_11 = 93;
pub const DW_OP_reg14: _bindgen_ty_11 = 94;
pub const DW_OP_reg15: _bindgen_ty_11 = 95;
pub const DW_OP_reg16: _bindgen_ty_11 = 96;
pub const DW_OP_reg17: _bindgen_ty_11 = 97;
pub const DW_OP_reg18: _bindgen_ty_11 = 98;
pub const DW_OP_reg19: _bindgen_ty_11 = 99;
pub const DW_OP_reg20: _bindgen_ty_11 = 100;
pub const DW_OP_reg21: _bindgen_ty_11 = 101;
pub const DW_OP_reg22: _bindgen_ty_11 = 102;
pub const DW_OP_reg23: _bindgen_ty_11 = 103;
pub const DW_OP_reg24: _bindgen_ty_11 = 104;
pub const DW_OP_reg25: _bindgen_ty_11 = 105;
pub const DW_OP_reg26: _bindgen_ty_11 = 106;
pub const DW_OP_reg27: _bindgen_ty_11 = 107;
pub const DW_OP_reg28: _bindgen_ty_11 = 108;
pub const DW_OP_reg29: _bindgen_ty_11 = 109;
pub const DW_OP_reg30: _bindgen_ty_11 = 110;
pub const DW_OP_reg31: _bindgen_ty_11 = 111;
pub const DW_OP_breg0: _bindgen_ty_11 = 112;
pub const DW_OP_breg1: _bindgen_ty_11 = 113;
pub const DW_OP_breg2: _bindgen_ty_11 = 114;
pub const DW_OP_breg3: _bindgen_ty_11 = 115;
pub const DW_OP_breg4: _bindgen_ty_11 = 116;
pub const DW_OP_breg5: _bindgen_ty_11 = 117;
pub const DW_OP_breg6: _bindgen_ty_11 = 118;
pub const DW_OP_breg7: _bindgen_ty_11 = 119;
pub const DW_OP_breg8: _bindgen_ty_11 = 120;
pub const DW_OP_breg9: _bindgen_ty_11 = 121;
pub const DW_OP_breg10: _bindgen_ty_11 = 122;
pub const DW_OP_breg11: _bindgen_ty_11 = 123;
pub const DW_OP_breg12: _bindgen_ty_11 = 124;
pub const DW_OP_breg13: _bindgen_ty_11 = 125;
pub const DW_OP_breg14: _bindgen_ty_11 = 126;
pub const DW_OP_breg15: _bindgen_ty_11 = 127;
pub const DW_OP_breg16: _bindgen_ty_11 = 128;
pub const DW_OP_breg17: _bindgen_ty_11 = 129;
pub const DW_OP_breg18: _bindgen_ty_11 = 130;
pub const DW_OP_breg19: _bindgen_ty_11 = 131;
pub const DW_OP_breg20: _bindgen_ty_11 = 132;
pub const DW_OP_breg21: _bindgen_ty_11 = 133;
pub const DW_OP_breg22: _bindgen_ty_11 = 134;
pub const DW_OP_breg23: _bindgen_ty_11 = 135;
pub const DW_OP_breg24: _bindgen_ty_11 = 136;
pub const DW_OP_breg25: _bindgen_ty_11 = 137;
pub const DW_OP_breg26: _bindgen_ty_11 = 138;
pub const DW_OP_breg27: _bindgen_ty_11 = 139;
pub const DW_OP_breg28: _bindgen_ty_11 = 140;
pub const DW_OP_breg29: _bindgen_ty_11 = 141;
pub const DW_OP_breg30: _bindgen_ty_11 = 142;
pub const DW_OP_breg31: _bindgen_ty_11 = 143;
pub const DW_OP_regx: _bindgen_ty_11 = 144;
pub const DW_OP_fbreg: _bindgen_ty_11 = 145;
pub const DW_OP_bregx: _bindgen_ty_11 = 146;
pub const DW_OP_piece: _bindgen_ty_11 = 147;
pub const DW_OP_deref_size: _bindgen_ty_11 = 148;
pub const DW_OP_xderef_size: _bindgen_ty_11 = 149;
pub const DW_OP_nop: _bindgen_ty_11 = 150;
pub const DW_OP_push_object_address: _bindgen_ty_11 = 151;
pub const DW_OP_call2: _bindgen_ty_11 = 152;
pub const DW_OP_call4: _bindgen_ty_11 = 153;
pub const DW_OP_call_ref: _bindgen_ty_11 = 154;
pub const DW_OP_form_tls_address: _bindgen_ty_11 = 155;
pub const DW_OP_call_frame_cfa: _bindgen_ty_11 = 156;
pub const DW_OP_bit_piece: _bindgen_ty_11 = 157;
pub const DW_OP_implicit_value: _bindgen_ty_11 = 158;
pub const DW_OP_stack_value: _bindgen_ty_11 = 159;
pub const DW_OP_implicit_pointer: _bindgen_ty_11 = 160;
pub const DW_OP_addrx: _bindgen_ty_11 = 161;
pub const DW_OP_constx: _bindgen_ty_11 = 162;
pub const DW_OP_entry_value: _bindgen_ty_11 = 163;
pub const DW_OP_const_type: _bindgen_ty_11 = 164;
pub const DW_OP_regval_type: _bindgen_ty_11 = 165;
pub const DW_OP_deref_type: _bindgen_ty_11 = 166;
pub const DW_OP_xderef_type: _bindgen_ty_11 = 167;
pub const DW_OP_convert: _bindgen_ty_11 = 168;
pub const DW_OP_reinterpret: _bindgen_ty_11 = 169;
pub const DW_OP_GNU_push_tls_address: _bindgen_ty_11 = 224;
pub const DW_OP_GNU_uninit: _bindgen_ty_11 = 240;
pub const DW_OP_GNU_encoded_addr: _bindgen_ty_11 = 241;
pub const DW_OP_GNU_implicit_pointer: _bindgen_ty_11 = 242;
pub const DW_OP_GNU_entry_value: _bindgen_ty_11 = 243;
pub const DW_OP_GNU_const_type: _bindgen_ty_11 = 244;
pub const DW_OP_GNU_regval_type: _bindgen_ty_11 = 245;
pub const DW_OP_GNU_deref_type: _bindgen_ty_11 = 246;
pub const DW_OP_GNU_convert: _bindgen_ty_11 = 247;
pub const DW_OP_GNU_reinterpret: _bindgen_ty_11 = 249;
pub const DW_OP_GNU_parameter_ref: _bindgen_ty_11 = 250;
pub const DW_OP_GNU_addr_index: _bindgen_ty_11 = 251;
pub const DW_OP_GNU_const_index: _bindgen_ty_11 = 252;
pub const DW_OP_GNU_variable_value: _bindgen_ty_11 = 253;
pub const DW_OP_lo_user: _bindgen_ty_11 = 224;
pub const DW_OP_hi_user: _bindgen_ty_11 = 255;
pub type _bindgen_ty_11 = ::libc::c_uint;
pub const DW_ATE_void: _bindgen_ty_12 = 0;
pub const DW_ATE_address: _bindgen_ty_12 = 1;
pub const DW_ATE_boolean: _bindgen_ty_12 = 2;
pub const DW_ATE_complex_float: _bindgen_ty_12 = 3;
pub const DW_ATE_float: _bindgen_ty_12 = 4;
pub const DW_ATE_signed: _bindgen_ty_12 = 5;
pub const DW_ATE_signed_char: _bindgen_ty_12 = 6;
pub const DW_ATE_unsigned: _bindgen_ty_12 = 7;
pub const DW_ATE_unsigned_char: _bindgen_ty_12 = 8;
pub const DW_ATE_imaginary_float: _bindgen_ty_12 = 9;
pub const DW_ATE_packed_decimal: _bindgen_ty_12 = 10;
pub const DW_ATE_numeric_string: _bindgen_ty_12 = 11;
pub const DW_ATE_edited: _bindgen_ty_12 = 12;
pub const DW_ATE_signed_fixed: _bindgen_ty_12 = 13;
pub const DW_ATE_unsigned_fixed: _bindgen_ty_12 = 14;
pub const DW_ATE_decimal_float: _bindgen_ty_12 = 15;
pub const DW_ATE_UTF: _bindgen_ty_12 = 16;
pub const DW_ATE_UCS: _bindgen_ty_12 = 17;
pub const DW_ATE_ASCII: _bindgen_ty_12 = 18;
pub const DW_ATE_lo_user: _bindgen_ty_12 = 128;
pub const DW_ATE_hi_user: _bindgen_ty_12 = 255;
pub type _bindgen_ty_12 = ::libc::c_uint;
pub const DW_DS_unsigned: _bindgen_ty_13 = 1;
pub const DW_DS_leading_overpunch: _bindgen_ty_13 = 2;
pub const DW_DS_trailing_overpunch: _bindgen_ty_13 = 3;
pub const DW_DS_leading_separate: _bindgen_ty_13 = 4;
pub const DW_DS_trailing_separate: _bindgen_ty_13 = 5;
pub type _bindgen_ty_13 = ::libc::c_uint;
pub const DW_END_default: _bindgen_ty_14 = 0;
pub const DW_END_big: _bindgen_ty_14 = 1;
pub const DW_END_little: _bindgen_ty_14 = 2;
pub const DW_END_lo_user: _bindgen_ty_14 = 64;
pub const DW_END_hi_user: _bindgen_ty_14 = 255;
pub type _bindgen_ty_14 = ::libc::c_uint;
pub const DW_ACCESS_public: _bindgen_ty_15 = 1;
pub const DW_ACCESS_protected: _bindgen_ty_15 = 2;
pub const DW_ACCESS_private: _bindgen_ty_15 = 3;
pub type _bindgen_ty_15 = ::libc::c_uint;
pub const DW_VIS_local: _bindgen_ty_16 = 1;
pub const DW_VIS_exported: _bindgen_ty_16 = 2;
pub const DW_VIS_qualified: _bindgen_ty_16 = 3;
pub type _bindgen_ty_16 = ::libc::c_uint;
pub const DW_VIRTUALITY_none: _bindgen_ty_17 = 0;
pub const DW_VIRTUALITY_virtual: _bindgen_ty_17 = 1;
pub const DW_VIRTUALITY_pure_virtual: _bindgen_ty_17 = 2;
pub type _bindgen_ty_17 = ::libc::c_uint;
pub const DW_LANG_C89: _bindgen_ty_18 = 1;
pub const DW_LANG_C: _bindgen_ty_18 = 2;
pub const DW_LANG_Ada83: _bindgen_ty_18 = 3;
pub const DW_LANG_C_plus_plus: _bindgen_ty_18 = 4;
pub const DW_LANG_Cobol74: _bindgen_ty_18 = 5;
pub const DW_LANG_Cobol85: _bindgen_ty_18 = 6;
pub const DW_LANG_Fortran77: _bindgen_ty_18 = 7;
pub const DW_LANG_Fortran90: _bindgen_ty_18 = 8;
pub const DW_LANG_Pascal83: _bindgen_ty_18 = 9;
pub const DW_LANG_Modula2: _bindgen_ty_18 = 10;
pub const DW_LANG_Java: _bindgen_ty_18 = 11;
pub const DW_LANG_C99: _bindgen_ty_18 = 12;
pub const DW_LANG_Ada95: _bindgen_ty_18 = 13;
pub const DW_LANG_Fortran95: _bindgen_ty_18 = 14;
pub const DW_LANG_PLI: _bindgen_ty_18 = 15;
pub const DW_LANG_ObjC: _bindgen_ty_18 = 16;
pub const DW_LANG_ObjC_plus_plus: _bindgen_ty_18 = 17;
pub const DW_LANG_UPC: _bindgen_ty_18 = 18;
pub const DW_LANG_D: _bindgen_ty_18 = 19;
pub const DW_LANG_Python: _bindgen_ty_18 = 20;
pub const DW_LANG_OpenCL: _bindgen_ty_18 = 21;
pub const DW_LANG_Go: _bindgen_ty_18 = 22;
pub const DW_LANG_Modula3: _bindgen_ty_18 = 23;
pub const DW_LANG_Haskell: _bindgen_ty_18 = 24;
pub const DW_LANG_C_plus_plus_03: _bindgen_ty_18 = 25;
pub const DW_LANG_C_plus_plus_11: _bindgen_ty_18 = 26;
pub const DW_LANG_OCaml: _bindgen_ty_18 = 27;
pub const DW_LANG_Rust: _bindgen_ty_18 = 28;
pub const DW_LANG_C11: _bindgen_ty_18 = 29;
pub const DW_LANG_Swift: _bindgen_ty_18 = 30;
pub const DW_LANG_Julia: _bindgen_ty_18 = 31;
pub const DW_LANG_Dylan: _bindgen_ty_18 = 32;
pub const DW_LANG_C_plus_plus_14: _bindgen_ty_18 = 33;
pub const DW_LANG_Fortran03: _bindgen_ty_18 = 34;
pub const DW_LANG_Fortran08: _bindgen_ty_18 = 35;
pub const DW_LANG_RenderScript: _bindgen_ty_18 = 36;
pub const DW_LANG_BLISS: _bindgen_ty_18 = 37;
pub const DW_LANG_lo_user: _bindgen_ty_18 = 32768;
pub const DW_LANG_Mips_Assembler: _bindgen_ty_18 = 32769;
pub const DW_LANG_hi_user: _bindgen_ty_18 = 65535;
pub type _bindgen_ty_18 = ::libc::c_uint;
pub const DW_ID_case_sensitive: _bindgen_ty_19 = 0;
pub const DW_ID_up_case: _bindgen_ty_19 = 1;
pub const DW_ID_down_case: _bindgen_ty_19 = 2;
pub const DW_ID_case_insensitive: _bindgen_ty_19 = 3;
pub type _bindgen_ty_19 = ::libc::c_uint;
pub const DW_CC_normal: _bindgen_ty_20 = 1;
pub const DW_CC_program: _bindgen_ty_20 = 2;
pub const DW_CC_nocall: _bindgen_ty_20 = 3;
pub const DW_CC_pass_by_reference: _bindgen_ty_20 = 4;
pub const DW_CC_pass_by_value: _bindgen_ty_20 = 5;
pub const DW_CC_lo_user: _bindgen_ty_20 = 64;
pub const DW_CC_hi_user: _bindgen_ty_20 = 255;
pub type _bindgen_ty_20 = ::libc::c_uint;
pub const DW_INL_not_inlined: _bindgen_ty_21 = 0;
pub const DW_INL_inlined: _bindgen_ty_21 = 1;
pub const DW_INL_declared_not_inlined: _bindgen_ty_21 = 2;
pub const DW_INL_declared_inlined: _bindgen_ty_21 = 3;
pub type _bindgen_ty_21 = ::libc::c_uint;
pub const DW_ORD_row_major: _bindgen_ty_22 = 0;
pub const DW_ORD_col_major: _bindgen_ty_22 = 1;
pub type _bindgen_ty_22 = ::libc::c_uint;
pub const DW_DSC_label: _bindgen_ty_23 = 0;
pub const DW_DSC_range: _bindgen_ty_23 = 1;
pub type _bindgen_ty_23 = ::libc::c_uint;
pub const DW_DEFAULTED_no: _bindgen_ty_24 = 0;
pub const DW_DEFAULTED_in_class: _bindgen_ty_24 = 1;
pub const DW_DEFAULTED_out_of_class: _bindgen_ty_24 = 2;
pub type _bindgen_ty_24 = ::libc::c_uint;
pub const DW_LNCT_path: _bindgen_ty_25 = 1;
pub const DW_LNCT_directory_index: _bindgen_ty_25 = 2;
pub const DW_LNCT_timestamp: _bindgen_ty_25 = 3;
pub const DW_LNCT_size: _bindgen_ty_25 = 4;
pub const DW_LNCT_MD5: _bindgen_ty_25 = 5;
pub const DW_LNCT_lo_user: _bindgen_ty_25 = 8192;
pub const DW_LNCT_hi_user: _bindgen_ty_25 = 16383;
pub type _bindgen_ty_25 = ::libc::c_uint;
pub const DW_LNS_copy: _bindgen_ty_26 = 1;
pub const DW_LNS_advance_pc: _bindgen_ty_26 = 2;
pub const DW_LNS_advance_line: _bindgen_ty_26 = 3;
pub const DW_LNS_set_file: _bindgen_ty_26 = 4;
pub const DW_LNS_set_column: _bindgen_ty_26 = 5;
pub const DW_LNS_negate_stmt: _bindgen_ty_26 = 6;
pub const DW_LNS_set_basic_block: _bindgen_ty_26 = 7;
pub const DW_LNS_const_add_pc: _bindgen_ty_26 = 8;
pub const DW_LNS_fixed_advance_pc: _bindgen_ty_26 = 9;
pub const DW_LNS_set_prologue_end: _bindgen_ty_26 = 10;
pub const DW_LNS_set_epilogue_begin: _bindgen_ty_26 = 11;
pub const DW_LNS_set_isa: _bindgen_ty_26 = 12;
pub type _bindgen_ty_26 = ::libc::c_uint;
pub const DW_LNE_end_sequence: _bindgen_ty_27 = 1;
pub const DW_LNE_set_address: _bindgen_ty_27 = 2;
pub const DW_LNE_define_file: _bindgen_ty_27 = 3;
pub const DW_LNE_set_discriminator: _bindgen_ty_27 = 4;
pub const DW_LNE_lo_user: _bindgen_ty_27 = 128;
pub const DW_LNE_NVIDIA_inlined_call: _bindgen_ty_27 = 144;
pub const DW_LNE_NVIDIA_set_function_name: _bindgen_ty_27 = 145;
pub const DW_LNE_hi_user: _bindgen_ty_27 = 255;
pub type _bindgen_ty_27 = ::libc::c_uint;
pub const DW_MACINFO_define: _bindgen_ty_28 = 1;
pub const DW_MACINFO_undef: _bindgen_ty_28 = 2;
pub const DW_MACINFO_start_file: _bindgen_ty_28 = 3;
pub const DW_MACINFO_end_file: _bindgen_ty_28 = 4;
pub const DW_MACINFO_vendor_ext: _bindgen_ty_28 = 255;
pub type _bindgen_ty_28 = ::libc::c_uint;
pub const DW_MACRO_define: _bindgen_ty_29 = 1;
pub const DW_MACRO_undef: _bindgen_ty_29 = 2;
pub const DW_MACRO_start_file: _bindgen_ty_29 = 3;
pub const DW_MACRO_end_file: _bindgen_ty_29 = 4;
pub const DW_MACRO_define_strp: _bindgen_ty_29 = 5;
pub const DW_MACRO_undef_strp: _bindgen_ty_29 = 6;
pub const DW_MACRO_import: _bindgen_ty_29 = 7;
pub const DW_MACRO_define_sup: _bindgen_ty_29 = 8;
pub const DW_MACRO_undef_sup: _bindgen_ty_29 = 9;
pub const DW_MACRO_import_sup: _bindgen_ty_29 = 10;
pub const DW_MACRO_define_strx: _bindgen_ty_29 = 11;
pub const DW_MACRO_undef_strx: _bindgen_ty_29 = 12;
pub const DW_MACRO_lo_user: _bindgen_ty_29 = 224;
pub const DW_MACRO_hi_user: _bindgen_ty_29 = 255;
pub type _bindgen_ty_29 = ::libc::c_uint;
pub const DW_RLE_end_of_list: _bindgen_ty_30 = 0;
pub const DW_RLE_base_addressx: _bindgen_ty_30 = 1;
pub const DW_RLE_startx_endx: _bindgen_ty_30 = 2;
pub const DW_RLE_startx_length: _bindgen_ty_30 = 3;
pub const DW_RLE_offset_pair: _bindgen_ty_30 = 4;
pub const DW_RLE_base_address: _bindgen_ty_30 = 5;
pub const DW_RLE_start_end: _bindgen_ty_30 = 6;
pub const DW_RLE_start_length: _bindgen_ty_30 = 7;
pub type _bindgen_ty_30 = ::libc::c_uint;
pub const DW_LLE_end_of_list: _bindgen_ty_31 = 0;
pub const DW_LLE_base_addressx: _bindgen_ty_31 = 1;
pub const DW_LLE_startx_endx: _bindgen_ty_31 = 2;
pub const DW_LLE_startx_length: _bindgen_ty_31 = 3;
pub const DW_LLE_offset_pair: _bindgen_ty_31 = 4;
pub const DW_LLE_default_location: _bindgen_ty_31 = 5;
pub const DW_LLE_base_address: _bindgen_ty_31 = 6;
pub const DW_LLE_start_end: _bindgen_ty_31 = 7;
pub const DW_LLE_start_length: _bindgen_ty_31 = 8;
pub type _bindgen_ty_31 = ::libc::c_uint;
pub const DW_LLE_GNU_end_of_list_entry: _bindgen_ty_32 = 0;
pub const DW_LLE_GNU_base_address_selection_entry: _bindgen_ty_32 = 1;
pub const DW_LLE_GNU_start_end_entry: _bindgen_ty_32 = 2;
pub const DW_LLE_GNU_start_length_entry: _bindgen_ty_32 = 3;
pub const DW_LLE_GNU_view_pair: _bindgen_ty_32 = 9;
pub type _bindgen_ty_32 = ::libc::c_uint;
pub const DW_SECT_INFO: _bindgen_ty_33 = 1;
pub const DW_SECT_ABBREV: _bindgen_ty_33 = 3;
pub const DW_SECT_LINE: _bindgen_ty_33 = 4;
pub const DW_SECT_LOCLISTS: _bindgen_ty_33 = 5;
pub const DW_SECT_STR_OFFSETS: _bindgen_ty_33 = 6;
pub const DW_SECT_MACRO: _bindgen_ty_33 = 7;
pub const DW_SECT_RNGLISTS: _bindgen_ty_33 = 8;
pub type _bindgen_ty_33 = ::libc::c_uint;
pub const DW_CFA_advance_loc: _bindgen_ty_34 = 64;
pub const DW_CFA_offset: _bindgen_ty_34 = 128;
pub const DW_CFA_restore: _bindgen_ty_34 = 192;
pub const DW_CFA_extended: _bindgen_ty_34 = 0;
pub const DW_CFA_nop: _bindgen_ty_34 = 0;
pub const DW_CFA_set_loc: _bindgen_ty_34 = 1;
pub const DW_CFA_advance_loc1: _bindgen_ty_34 = 2;
pub const DW_CFA_advance_loc2: _bindgen_ty_34 = 3;
pub const DW_CFA_advance_loc4: _bindgen_ty_34 = 4;
pub const DW_CFA_offset_extended: _bindgen_ty_34 = 5;
pub const DW_CFA_restore_extended: _bindgen_ty_34 = 6;
pub const DW_CFA_undefined: _bindgen_ty_34 = 7;
pub const DW_CFA_same_value: _bindgen_ty_34 = 8;
pub const DW_CFA_register: _bindgen_ty_34 = 9;
pub const DW_CFA_remember_state: _bindgen_ty_34 = 10;
pub const DW_CFA_restore_state: _bindgen_ty_34 = 11;
pub const DW_CFA_def_cfa: _bindgen_ty_34 = 12;
pub const DW_CFA_def_cfa_register: _bindgen_ty_34 = 13;
pub const DW_CFA_def_cfa_offset: _bindgen_ty_34 = 14;
pub const DW_CFA_def_cfa_expression: _bindgen_ty_34 = 15;
pub const DW_CFA_expression: _bindgen_ty_34 = 16;
pub const DW_CFA_offset_extended_sf: _bindgen_ty_34 = 17;
pub const DW_CFA_def_cfa_sf: _bindgen_ty_34 = 18;
pub const DW_CFA_def_cfa_offset_sf: _bindgen_ty_34 = 19;
pub const DW_CFA_val_offset: _bindgen_ty_34 = 20;
pub const DW_CFA_val_offset_sf: _bindgen_ty_34 = 21;
pub const DW_CFA_val_expression: _bindgen_ty_34 = 22;
pub const DW_CFA_low_user: _bindgen_ty_34 = 28;
pub const DW_CFA_MIPS_advance_loc8: _bindgen_ty_34 = 29;
pub const DW_CFA_GNU_window_save: _bindgen_ty_34 = 45;
pub const DW_CFA_AARCH64_negate_ra_state: _bindgen_ty_34 = 45;
pub const DW_CFA_GNU_args_size: _bindgen_ty_34 = 46;
pub const DW_CFA_GNU_negative_offset_extended: _bindgen_ty_34 = 47;
pub const DW_CFA_high_user: _bindgen_ty_34 = 63;
pub type _bindgen_ty_34 = ::libc::c_uint;
pub const DW_CIE_ID_32: _bindgen_ty_35 = 4294967295;
pub const DW_CIE_ID_64: _bindgen_ty_35 = 18446744073709551615;
pub type _bindgen_ty_35 = ::libc::c_ulonglong;
pub const DW_EH_PE_absptr: _bindgen_ty_36 = 0;
pub const DW_EH_PE_omit: _bindgen_ty_36 = 255;
pub const DW_EH_PE_uleb128: _bindgen_ty_36 = 1;
pub const DW_EH_PE_udata2: _bindgen_ty_36 = 2;
pub const DW_EH_PE_udata4: _bindgen_ty_36 = 3;
pub const DW_EH_PE_udata8: _bindgen_ty_36 = 4;
pub const DW_EH_PE_sleb128: _bindgen_ty_36 = 9;
pub const DW_EH_PE_sdata2: _bindgen_ty_36 = 10;
pub const DW_EH_PE_sdata4: _bindgen_ty_36 = 11;
pub const DW_EH_PE_sdata8: _bindgen_ty_36 = 12;
pub const DW_EH_PE_signed: _bindgen_ty_36 = 8;
pub const DW_EH_PE_pcrel: _bindgen_ty_36 = 16;
pub const DW_EH_PE_textrel: _bindgen_ty_36 = 32;
pub const DW_EH_PE_datarel: _bindgen_ty_36 = 48;
pub const DW_EH_PE_funcrel: _bindgen_ty_36 = 64;
pub const DW_EH_PE_aligned: _bindgen_ty_36 = 80;
pub const DW_EH_PE_indirect: _bindgen_ty_36 = 128;
pub type _bindgen_ty_36 = ::libc::c_uint;
